export interface AvatarPreset {
  id: string;
  name: string;
  hindiName: string;
  tagline: string;
  src: string;
  category: "mountains" | "heritage" | "road" | "nature" | "lifestyle" | "coastal" | "expedition";
}

export const AVATAR_PRESETS: AvatarPreset[] = [
  {
    id: "himalayan-explorer",
    name: "Himalayan Explorer",
    hindiName: "हिमालयी खोजी",
    tagline: "High alpine ridge walks & snow line expeditions",
    src: "/avatars/himalayan-explorer.svg",
    category: "mountains",
  },
  {
    id: "mountain-camper",
    name: "Mountain Camper",
    hindiName: "पहाड़ी कैम्पर",
    tagline: "A-frame tents under starry Himalayan night skies",
    src: "/avatars/mountain-camper.svg",
    category: "mountains",
  },
  {
    id: "road-tripper",
    name: "Road Tripper",
    hindiName: "हाईवे राइडर",
    tagline: "NH-44 dawn sprints, roadside dhabas & milestones",
    src: "/avatars/road-tripper.svg",
    category: "road",
  },
  {
    id: "heritage-wanderer",
    name: "Heritage Wanderer",
    hindiName: "शाही मुसाफ़िर",
    tagline: "Sandstone forts, jharokha arches & desert sunsets",
    src: "/avatars/heritage-wanderer.svg",
    category: "heritage",
  },
  {
    id: "river-roamer",
    name: "River Roamer",
    hindiName: "नदी पथिक",
    tagline: "Sacred ghat currents, wooden boats & dawn mist",
    src: "/avatars/river-roamer.svg",
    category: "nature",
  },
  {
    id: "desert-nomad",
    name: "Desert Nomad",
    hindiName: "मरुस्थल यात्री",
    tagline: "Golden sand dune ripples & starry desert nights",
    src: "/avatars/desert-nomad.svg",
    category: "heritage",
  },
  {
    id: "forest-walker",
    name: "Forest Walker",
    hindiName: "वन पथिक",
    tagline: "Deodar pine canopies & misty jungle walking trails",
    src: "/avatars/forest-walker.svg",
    category: "nature",
  },
  {
    id: "trail-photographer",
    name: "Trail Photographer",
    hindiName: "दृश्य छायाकार",
    tagline: "Mechanical rangefinders capturing mountain light",
    src: "/avatars/trail-photographer.svg",
    category: "lifestyle",
  },
  {
    id: "backpacker",
    name: "Backpacker",
    hindiName: "झोलाछाप मुसाफ़िर",
    tagline: "Rugged rucksacks, trekking poles & open horizons",
    src: "/avatars/backpacker.svg",
    category: "lifestyle",
  },
  {
    id: "cafe-wanderer",
    name: "Café Wanderer",
    hindiName: "कैफ़े खोजी",
    tagline: "Steaming mountain chai & hillside wooden desks",
    src: "/avatars/cafe-wanderer.svg",
    category: "lifestyle",
  },
  {
    id: "night-traveller",
    name: "Night Traveller",
    hindiName: "निशाचर राही",
    tagline: "Crescent moon highways & campfire sparks",
    src: "/avatars/night-traveller.svg",
    category: "road",
  },
  {
    id: "wayfarer",
    name: "The Wayfarer",
    hindiName: "राही",
    tagline: "Timeless Indian explorer charting quiet roads",
    src: "/avatars/wayfarer.svg",
    category: "lifestyle",
  },
  {
    id: "monsoon-trekker",
    name: "Monsoon Trekker",
    hindiName: "मानसूनी ट्रेकर",
    tagline: "Misty Western Ghats trails, waterfalls & green cascades",
    src: "/avatars/monsoon-trekker.svg",
    category: "nature",
  },
  {
    id: "snow-chaser",
    name: "Snow Chaser",
    hindiName: "हिम खोजी",
    tagline: "Winter powder passes, frozen lakes & high blizzard paths",
    src: "/avatars/snow-chaser.svg",
    category: "mountains",
  },
  {
    id: "bike-nomad",
    name: "Bike Nomad",
    hindiName: "बाइक मुसाफ़िर",
    tagline: "Rumbling Himalayan motorcycle odysseys & hairpin bends",
    src: "/avatars/bike-nomad.svg",
    category: "road",
  },
  {
    id: "train-traveller",
    name: "Train Traveller",
    hindiName: "रेल यात्री",
    tagline: "Chai in clay kulhads by the open sleeper window",
    src: "/avatars/train-traveller.svg",
    category: "lifestyle",
  },
  {
    id: "temple-explorer",
    name: "Temple Explorer",
    hindiName: "तीर्थ पथिक",
    tagline: "Ancient stone sanctums, bell chimes & evening aartis",
    src: "/avatars/temple-explorer.svg",
    category: "heritage",
  },
  {
    id: "coastal-drifter",
    name: "Coastal Drifter",
    hindiName: "तटीय घुमक्कड़",
    tagline: "Coconut palm shores, ocean shacks & sea breeze trails",
    src: "/avatars/coastal-drifter.svg",
    category: "coastal",
  },
  {
    id: "wildlife-explorer",
    name: "Wildlife Explorer",
    hindiName: "वन्य खोजी",
    tagline: "Tiger territories, sal forests & birding hideaways",
    src: "/avatars/wildlife-explorer.svg",
    category: "nature",
  },
  {
    id: "stargazer",
    name: "Stargazer",
    hindiName: "तारादर्शी",
    tagline: "Milky Way skies over remote Himalayan high passes",
    src: "/avatars/stargazer.svg",
    category: "mountains",
  },
  {
    id: "solo-traveller",
    name: "Solo Traveller",
    hindiName: "एकाकी मुसाफ़िर",
    tagline: "Quiet independence, solitary paths & spontaneous turns",
    src: "/avatars/solo-traveller.svg",
    category: "lifestyle",
  },
  {
    id: "group-traveller",
    name: "Group Traveller",
    hindiName: "सहयात्री संघ",
    tagline: "Shared expedition laughter, group trails & chai stops",
    src: "/avatars/group-traveller.svg",
    category: "lifestyle",
  },
  {
    id: "old-school-explorer",
    name: "Old-School Explorer",
    hindiName: "क्लासिक खोजी",
    tagline: "Brass compasses, topographic maps & paper journals",
    src: "/avatars/old-school-explorer.svg",
    category: "expedition",
  },
  {
    id: "backpack-photographer",
    name: "Backpack Photographer",
    hindiName: "लेंस मुसाफ़िर",
    tagline: "Golden hour ridgelines & heavy telephoto journeys",
    src: "/avatars/backpack-photographer.svg",
    category: "lifestyle",
  },
  {
    id: "valley-wanderer",
    name: "Valley Wanderer",
    hindiName: "वादी पथिक",
    tagline: "Wildflower meadows, deodar slopes & babbling brooks",
    src: "/avatars/valley-wanderer.svg",
    category: "nature",
  },
  {
    id: "campfire-traveller",
    name: "Campfire Traveller",
    hindiName: "अलाव मुसाफ़िर",
    tagline: "Crackling pine logs, travel tales & starry warmth",
    src: "/avatars/campfire-traveller.svg",
    category: "lifestyle",
  },
  {
    id: "urban-explorer",
    name: "Urban Explorer",
    hindiName: "नगर खोजी",
    tagline: "Hidden alleyways, heritage bakeries & rooftop culture",
    src: "/avatars/urban-explorer.svg",
    category: "lifestyle",
  },
  {
    id: "monsoon-rider",
    name: "Monsoon Rider",
    hindiName: "मेघ सवार",
    tagline: "Rain-slicked mountain passes & mist-shrouded ghats",
    src: "/avatars/monsoon-rider.svg",
    category: "road",
  },
  {
    id: "desert-rider",
    name: "Desert Rider",
    hindiName: "रेतीला राइडर",
    tagline: "Golden dune sprints & twilight desert camp horizons",
    src: "/avatars/desert-rider.svg",
    category: "road",
  },
  {
    id: "expedition-leader",
    name: "Expedition Leader",
    hindiName: "अभियान नायक",
    tagline: "High mountain leadership, summit routes & valley stewardship",
    src: "/avatars/expedition-leader.svg",
    category: "expedition",
  },
];

export function getAvatarPresetById(id?: string | null): AvatarPreset | undefined {
  if (!id) return undefined;
  return AVATAR_PRESETS.find((p) => p.id === id);
}
