/**
 * VANVAS Canonical Destination Registry & Localization Standard
 * Single authoritative source of truth across Explore, One-Day, Treks, Plan, Trips, Nearby, and Copilot.
 */

export interface CanonicalDestination {
  id: string;
  name: string;
  slug: string;
  hindi_name: string;
  name_en?: string;
  name_hi?: string;
  subtitle_en?: string;
  subtitle_hi?: string;
  description_en?: string;
  description_hi?: string;
  state: string;
  region: string;
  category?: string;
  tagline: string;
  description: string;
  hero_image: string;
  hero_artwork?: string;
  hero_photo?: string;
  latitude: number;
  longitude: number;
  altitude_meters: number;
  best_time_to_visit: string;
  weather_type: string;
  one_day_available?: boolean;
  trek_available?: boolean;
  nearby_available?: boolean;
  is_featured: boolean;
  is_curated: boolean;
}

export const CANONICAL_DESTINATIONS: CanonicalDestination[] = [
  {
    id: "dest-manali",
    name: "Manali",
    name_en: "Manali",
    name_hi: "मनाली",
    slug: "manali",
    hindi_name: "मनाली",
    state: "Himachal Pradesh",
    region: "Himalayan",
    category: "Mountain Retreat",
    tagline: "Pine-scented mountain air, riverside stone cafés, and high alpine trails.",
    subtitle_en: "Pine-scented mountain air, riverside stone cafés, and high alpine trails.",
    subtitle_hi: "चीड़ की खुशबू वाली हवा, नदी किनारे कैफ़े और अल्पाइन रास्ते।",
    description: "Nestled in the Beas River Valley, Manali blends rustic Himalayan charm with vibrant café culture and gateway routes to high altitude passes.",
    description_en: "Nestled in the Beas River Valley, Manali blends rustic Himalayan charm with vibrant café culture and gateway routes to high altitude passes.",
    description_hi: "ब्यास नदी घाटी में बसा मनाली पारंपरिक हिमालयी संस्कृति और जीवंत कैफ़े जीवन का अनूठा संगम प्रस्तुत करता है।",
    hero_image: "/images/destinations/manali/hero.jpg",
    hero_artwork: "/artworks/manali.jpg",
    hero_photo: "/images/destinations/manali/hero.jpg",
    latitude: 32.2396,
    longitude: 77.1887,
    altitude_meters: 2050,
    best_time_to_visit: "October to June",
    weather_type: "Alpine Mist / Cool",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-rishikesh",
    name: "Rishikesh",
    name_en: "Rishikesh",
    name_hi: "ऋषिकेश",
    slug: "rishikesh",
    hindi_name: "ऋषिकेश",
    state: "Uttarakhand",
    region: "Himalayan Foothills",
    category: "Spiritual & Adventure",
    tagline: "Turquoise Ganga currents, cliffside meditation, and rapid adventures.",
    subtitle_en: "Turquoise Ganga currents, cliffside meditation, and rapid adventures.",
    subtitle_hi: "नीली गंगा की धारा, योग साधना और रोमांचक रिवर राफ़्टिंग।",
    description: "The yoga capital of the world resting on the banks of the sacred Ganges, where jungle serenity meets world-class river rafting and sunset aartis.",
    description_en: "The yoga capital of the world resting on the banks of the sacred Ganges, where jungle serenity meets world-class river rafting and sunset aartis.",
    description_hi: "पवित्र गंगा के तट पर स्थित योग और अध्यात्म की वैश्विक राजधानी, जहाँ संध्या आरती और प्राकृतिक शांति का अद्भुत अनुभव मिलता है।",
    hero_image: "/images/destinations/rishikesh/hero.jpg",
    hero_artwork: "/artworks/rishikesh.jpg",
    hero_photo: "/images/destinations/rishikesh/hero.jpg",
    latitude: 30.0869,
    longitude: 78.2676,
    altitude_meters: 372,
    best_time_to_visit: "September to May",
    weather_type: "Pleasant / River Breeze",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-tungnath-chandrashila",
    name: "Tungnath–Chandrashila Trek",
    name_en: "Tungnath–Chandrashila",
    name_hi: "तुंगनाथ–चंद्रशिला",
    slug: "tungnath-chandrashila",
    hindi_name: "तुंगनाथ–चंद्रशिला",
    state: "Uttarakhand",
    region: "Garhwal Himalayas",
    category: "High Altitude Trek",
    tagline: "World's highest Shiva shrine, alpine rhododendron bugyals, and a 360° summit over Chaukhamba.",
    subtitle_en: "World's highest Shiva shrine, alpine rhododendron bugyals, and a 360° summit over Chaukhamba.",
    subtitle_hi: "विश्व का सबसे ऊँचा शिव मंदिर, बुरांश के बुग्याल और चौखंभा का 360° विहंगम दृश्य।",
    description: "An iconic Garhwal Himalayan trail ascending from the meadows of Chopta (2,680m) through alpine rhododendrons to the ancient stone Tungnath Temple (3,680m) and continuing 1.5 km to the Chandrashila Summit (4,000m) with sweeping views of Chaukhamba, Trishul, and Nanda Devi.",
    description_en: "An iconic Garhwal Himalayan trail ascending from the meadows of Chopta (2,680m) through alpine rhododendrons to the ancient stone Tungnath Temple (3,680m) and continuing 1.5 km to the Chandrashila Summit (4,000m) with sweeping views of Chaukhamba, Trishul, and Nanda Devi.",
    description_hi: "चोपता के मखमली बुग्यालों से शुरू होकर प्राचीन तुंगनाथ मंदिर और 4000 मीटर ऊँचे चंद्रशिला शिखर तक जाने वाला अद्वितीय हिमालयी ट्रेक।",
    hero_image: "/images/destinations/tungnath-chandrashila/hero.jpg",
    hero_artwork: "/artworks/fallback_himalayan.jpg",
    hero_photo: "/images/destinations/tungnath-chandrashila/hero.jpg",
    latitude: 30.4886,
    longitude: 79.2173,
    altitude_meters: 4000,
    best_time_to_visit: "April to November",
    weather_type: "High Alpine Crisp Air",
    one_day_available: false,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-kainchi-dham",
    name: "Kainchi Dham",
    name_en: "Kainchi Dham",
    name_hi: "कैंची धाम",
    slug: "kainchi-dham",
    hindi_name: "कैंची धाम",
    state: "Uttarakhand",
    region: "Kumaon Hills",
    category: "Sacred Ashram & Valley",
    tagline: "Neem Karoli Baba's sacred riverside ashram nestled in pine-scented Kumaoni valleys.",
    subtitle_en: "Neem Karoli Baba's sacred riverside ashram nestled in pine-scented Kumaoni valleys.",
    subtitle_hi: "नीम करौली बाबा का पावन आश्रम, कल-कल बहती पहाड़ी नदी और देवदार के घने वन।",
    description: "Established in 1962 by the revered mystic Neem Karoli Baba, Kainchi Dham sits between two scenic mountain hills in Nainital district. Renowned worldwide as a sanctuary of immense spiritual peace, chanting, and selfless service.",
    description_en: "Established in 1962 by the revered mystic Neem Karoli Baba, Kainchi Dham sits between two scenic mountain hills in Nainital district. Renowned worldwide as a sanctuary of immense spiritual peace, chanting, and selfless service.",
    description_hi: "सन् 1962 में परम पूज्य नीम करौली बाबा द्वारा स्थापित कैंची धाम नैनीताल की सुरम्य वादियों में स्थित एक अत्यंत पवित्र आध्यात्मिक तीर्थ है।",
    hero_image: "/images/destinations/kainchi-dham/hero.jpg",
    hero_artwork: "/artworks/kainchi-dham.jpg",
    hero_photo: "/images/destinations/kainchi-dham/hero.jpg",
    latitude: 29.4239,
    longitude: 79.5165,
    altitude_meters: 1400,
    best_time_to_visit: "Round the Year (Best: March to June & Sept to Nov)",
    weather_type: "Pleasant Mountain River Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-kasol",
    name: "Kasol",
    name_en: "Kasol",
    name_hi: "कसोल",
    slug: "kasol",
    hindi_name: "कसोल",
    state: "Himachal Pradesh",
    region: "Parvati Valley",
    category: "River Gorge & Valley",
    tagline: "Mystic deodar canopies, roaring emerald waters, and bohemian trails.",
    subtitle_en: "Mystic deodar canopies, roaring emerald waters, and bohemian trails.",
    subtitle_hi: "पार्वती नदी की गर्जना, देवदार के वन और शांत पहाड़ी पगडंडियाँ।",
    description: "A tranquil haven in Parvati Valley famous for Israeli bakeries, pine-forested riverside hikes to Chalal and Tosh, and unmatched mountain peace.",
    description_en: "A tranquil haven in Parvati Valley famous for Israeli bakeries, pine-forested riverside hikes to Chalal and Tosh, and unmatched mountain peace.",
    description_hi: "पार्वती घाटी का एक शांत कोना, जो देवदार के जंगलों, स्वादिष्ट बेकरी और तोश व चालल जैसे शांत ट्रेल्स के लिए जाना जाता है।",
    hero_image: "/images/destinations/kasol/hero.jpg",
    hero_artwork: "/artworks/kasol.jpg",
    hero_photo: "/images/destinations/kasol/hero.jpg",
    latitude: 32.0100,
    longitude: 77.3150,
    altitude_meters: 1580,
    best_time_to_visit: "March to June & Sept to Nov",
    weather_type: "Crisp Mountain Mist",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-dharamshala",
    name: "Dharamshala",
    name_en: "Dharamshala",
    name_hi: "धर्मशाला",
    slug: "dharamshala",
    hindi_name: "धर्मशाला",
    state: "Himachal Pradesh",
    region: "Kangra Valley",
    category: "Tibetan Heritage & Ridge",
    tagline: "Prayer flags in the mist, Tibetan heritage, and the mighty Dhauladhar ridge.",
    subtitle_en: "Prayer flags in the mist, Tibetan heritage, and the mighty Dhauladhar ridge.",
    subtitle_hi: "धौलाधार की बर्फीली चोटियाँ, तिब्बती मठ और शांत देवदार वन।",
    description: "Home of the Dalai Lama, surrounded by cedar forests and dramatic snow-capped peaks with authentic momos and serene monasteries.",
    description_en: "Home of the Dalai Lama, surrounded by cedar forests and dramatic snow-capped peaks with authentic momos and serene monasteries.",
    description_hi: "कांगड़ा घाटी में धौलाधार की तलहटी पर बसा धर्मशाला तिब्बती संस्कृति, बौद्ध मठों और शांत वादियों का प्रसिद्ध केंद्र है।",
    hero_image: "/images/destinations/dharamshala/hero.jpg",
    hero_artwork: "/artworks/dharamshala.jpg",
    hero_photo: "/images/destinations/dharamshala/hero.jpg",
    latitude: 32.2190,
    longitude: 76.3234,
    altitude_meters: 1457,
    best_time_to_visit: "September to June",
    weather_type: "Misty Cedar Air",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-goa",
    name: "Goa",
    name_en: "Goa",
    name_hi: "गोवा",
    slug: "goa",
    hindi_name: "गोवा",
    state: "Goa",
    region: "Coastal Western Ghats",
    category: "Coastal Heritage",
    tagline: "Golden palms, Portuguese villas, beach shack sunsets, and spice farms.",
    subtitle_en: "Golden palms, Portuguese villas, beach shack sunsets, and spice farms.",
    subtitle_hi: "नारियल के झुरमुट, पुर्तगाली हवेलियाँ और सुनहरे समुद्री तट।",
    description: "Beyond the crowded tourist strips lie sleepy riverside villages, historic Latin quarters, vibrant night flea markets, and tranquil cliff beaches.",
    description_en: "Beyond the crowded tourist strips lie sleepy riverside villages, historic Latin quarters, vibrant night flea markets, and tranquil cliff beaches.",
    description_hi: "अरब सागर के किनारे बसा गोवा अपने पुर्तगाली स्थापत्य, शांत बैकवाटर्स, और मनमोहक सूर्यास्त के लिए विख्यात है।",
    hero_image: "/images/destinations/goa/hero.jpg",
    hero_artwork: "/artworks/goa.jpg",
    hero_photo: "/images/destinations/goa/hero.jpg",
    latitude: 15.2993,
    longitude: 74.1240,
    altitude_meters: 10,
    best_time_to_visit: "November to April",
    weather_type: "Warm Coastal Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-jaipur",
    name: "Jaipur",
    name_en: "Jaipur",
    name_hi: "जयपुर",
    slug: "jaipur",
    hindi_name: "जयपुर",
    state: "Rajasthan",
    region: "Royal Heritage",
    category: "Royal Forts & Bazaars",
    tagline: "Terracotta ramparts, historic havelis, rich kachoris, and artisan crafts.",
    subtitle_en: "Terracotta ramparts, historic havelis, rich kachoris, and artisan crafts.",
    subtitle_hi: "गुलाबी हवेलियाँ, आमेर का भव्य किला और समृद्ध राजस्थानी संस्कृति।",
    description: "The Pink City where regal hill forts overlook bustling bazaars full of blue pottery, block-printed fabrics, and royal Rajasthani delicacies.",
    description_en: "The Pink City where regal hill forts overlook bustling bazaars full of blue pottery, block-printed fabrics, and royal Rajasthani delicacies.",
    description_hi: "राजस्थान की गुलाबी नगरी, जहाँ आमेर व नाहरगढ़ के किले, हवा महल और पारंपरिक बाज़ार पर्यटकों को आकर्षित करते हैं।",
    hero_image: "/images/destinations/jaipur/hero.jpg",
    hero_artwork: "/artworks/jaipur.jpg",
    hero_photo: "/images/destinations/jaipur/hero.jpg",
    latitude: 26.9124,
    longitude: 75.7873,
    altitude_meters: 431,
    best_time_to_visit: "October to March",
    weather_type: "Dry Heritage Warmth",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-murthal",
    name: "Murthal (GT Road)",
    name_en: "Murthal",
    name_hi: "मुरथल",
    slug: "murthal",
    hindi_name: "मुरथल",
    state: "Haryana",
    region: "GT Road Corridor",
    category: "Roadside Dhaba Culture",
    tagline: "Hot tandoori parathas with white butter, clay tandoors, and legendary GT Road highway culture.",
    subtitle_en: "Hot tandoori parathas with white butter, clay tandoors, and legendary GT Road highway culture.",
    subtitle_hi: "मक्खन से लबालब गरमा-गरम तंदूरी परांठे और प्रसिद्ध जीटी रोड ढाबा संस्कृति।",
    description: "Located along NH-44 in Sonipat district, Murthal is the capital of north Indian road trips, renowned for 24/7 legendary dhabas like Amrik Sukhdev and Haveli.",
    description_en: "Located along NH-44 in Sonipat district, Murthal is the capital of north Indian road trips, renowned for 24/7 legendary dhabas like Amrik Sukhdev and Haveli.",
    description_hi: "एनएच-44 पर स्थित मुरथल उत्तर भारत का सबसे लोकप्रिय हाईवे ढाबा केंद्र है जहाँ तंदूरी परांठे और कुल्हड़ चाय की महक बिखरी रहती है।",
    hero_image: "/images/destinations/murthal/hero.jpg",
    hero_artwork: "/artworks/murthal.jpg",
    hero_photo: "/images/destinations/murthal/hero.jpg",
    latitude: 29.0289,
    longitude: 77.0707,
    altitude_meters: 224,
    best_time_to_visit: "Round the Year",
    weather_type: "Highway Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-agra",
    name: "Agra",
    name_en: "Agra",
    name_hi: "आगरा",
    slug: "agra",
    hindi_name: "आगरा",
    state: "Uttar Pradesh",
    region: "Yamuna Heritage Corridor",
    category: "Mughal Architecture & Heritage",
    tagline: "The timeless marble poetry of the Taj Mahal, Agra Fort, and rich Yamuna river sunsets.",
    subtitle_en: "The timeless marble poetry of the Taj Mahal, Agra Fort, and rich Yamuna river sunsets.",
    subtitle_hi: "ताजमहल का श्वेत संगमरमर, भव्य आगरा किला और यमुना का सुरम्य सूर्यास्त।",
    description: "Home to the Taj Mahal and Agra Fort, Agra combines world-renowned Mughal sandstone architecture with bustling petha sweet lanes and riverside promenades.",
    description_en: "Home to the Taj Mahal and Agra Fort, Agra combines world-renowned Mughal sandstone architecture with bustling petha sweet lanes and riverside promenades.",
    description_hi: "यमुना किनारे बसा ऐतिहासिक आगरा शहर अपने विश्वप्रसिद्ध ताजमहल, लाल किले और सदियों पुराने पेठा बाज़ारों के लिए जाना जाता है।",
    hero_image: "/images/destinations/agra/hero.jpg",
    hero_artwork: "/artworks/agra.jpg",
    hero_photo: "/images/destinations/agra/hero.jpg",
    latitude: 27.1767,
    longitude: 78.0081,
    altitude_meters: 171,
    best_time_to_visit: "October to March",
    weather_type: "Pleasant Heritage Winter",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-mathura-vrindavan",
    name: "Mathura & Vrindavan",
    name_en: "Mathura & Vrindavan",
    name_hi: "मथुरा और वृन्दावन",
    slug: "mathura-vrindavan",
    hindi_name: "मथुरा और वृन्दावन",
    state: "Uttar Pradesh",
    region: "Braj Bhoomi",
    category: "Spiritual & Temple Heritage",
    tagline: "Sacred Yamuna aartis, Banke Bihari blessings, and glowing white marble of Prem Mandir.",
    subtitle_en: "Sacred Yamuna aartis, Banke Bihari blessings, and glowing white marble of Prem Mandir.",
    subtitle_hi: "बांके बिहारी के दर्शन, प्रेम मंदिर की अलौकिक छटा और यमुना जी की पावन आरती।",
    description: "The divine heartland of Braj Bhoomi, featuring Prem Mandir, Shri Krishna Janmabhoomi, Banke Bihari Temple, and holy evening ghat aartis on the Yamuna.",
    description_en: "The divine heartland of Braj Bhoomi, featuring Prem Mandir, Shri Krishna Janmabhoomi, Banke Bihari Temple, and holy evening ghat aartis on the Yamuna.",
    description_hi: "ब्रज भूमि का पावन तीर्थ, जहाँ बांके बिहारी मंदिर, प्रेम मंदिर और यमुना के विश्राम घाट पर भक्ति और शांति का अद्वितीय संगम होता है।",
    hero_image: "/images/destinations/mathura-vrindavan/hero.jpg",
    hero_artwork: "/artworks/mathura-vrindavan.jpg",
    hero_photo: "/images/destinations/mathura-vrindavan/hero.jpg",
    latitude: 27.5706,
    longitude: 77.6599,
    altitude_meters: 178,
    best_time_to_visit: "September to March",
    weather_type: "Pleasant Temple Atmosphere",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-neemrana",
    name: "Neemrana Fort",
    name_en: "Neemrana",
    name_hi: "नीमराना",
    slug: "neemrana",
    hindi_name: "नीमराना",
    state: "Rajasthan",
    region: "Aravalli Heritage",
    category: "Hill Fort Palace",
    tagline: "15th-century stepped fortress palace carved into Aravalli cliffs along the Jaipur Highway.",
    subtitle_en: "15th-century stepped fortress palace carved into Aravalli cliffs along the Jaipur Highway.",
    subtitle_hi: "अरावली की पहाड़ियों में सीढ़ीदार 15वीं सदी का भव्य नीमराना फोर्ट पैलेस।",
    description: "Perched majestically on Aravalli hillocks along NH-48, Neemrana Fort Palace offers 14 stepped levels of Rajput architecture, zip-lining, and sunset views.",
    description_en: "Perched majestically on Aravalli hillocks along NH-48, Neemrana Fort Palace offers 14 stepped levels of Rajput architecture, zip-lining, and sunset views.",
    description_hi: "दिल्ली-जयपुर हाईवे पर स्थित 15वीं सदी का सीढ़ीदार किला जहाँ राजस्थानी स्थापत्य और अरावली का सुंदर परिदृश्य मिलता है।",
    hero_image: "/images/destinations/neemrana/hero.jpg",
    hero_artwork: "/artworks/neemrana.jpg",
    hero_photo: "/images/destinations/neemrana/hero.jpg",
    latitude: 27.9942,
    longitude: 76.3869,
    altitude_meters: 340,
    best_time_to_visit: "September to April",
    weather_type: "Crisp Heritage Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-damdama-sohna",
    name: "Damdama & Sohna",
    name_en: "Damdama Lake",
    name_hi: "दमदमा और सोहना",
    slug: "damdama-sohna",
    hindi_name: "दमदमा और सोहना",
    state: "Haryana",
    region: "Aravalli Foothills",
    category: "Lake & Adventure Escape",
    tagline: "Tranquil lake waters framed by rugged Aravalli rocky ridges, rowing boats, and rustic trails.",
    subtitle_en: "Tranquil lake waters framed by rugged Aravalli rocky ridges, rowing boats, and rustic trails.",
    subtitle_hi: "अरावली की शांत झील, नौकायन और हरियाली से घिरी प्राकृतिक सैरगाह।",
    description: "One of Haryana's largest natural lakes, resting at the base of the Aravalli hills near Sohna, perfect for boating, rock climbing, and weekend picnics.",
    description_en: "One of Haryana's largest natural lakes, resting at the base of the Aravalli hills near Sohna, perfect for boating, rock climbing, and weekend picnics.",
    description_hi: "गुड़गांव के पास अरावली की तलहटी में स्थित दमदमा झील नौकायन और सप्ताहांत की शांति के लिए एक आदर्श स्थान है।",
    hero_image: "/images/destinations/damdama-sohna/hero.jpg",
    hero_artwork: "/artworks/damdama-sohna.jpg",
    hero_photo: "/images/destinations/damdama-sohna/hero.jpg",
    latitude: 28.3075,
    longitude: 77.0617,
    altitude_meters: 220,
    best_time_to_visit: "October to March",
    weather_type: "Lakeside Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-alwar-siliserh",
    name: "Alwar & Siliserh Lake",
    name_en: "Alwar & Siliserh",
    name_hi: "अलवर और सिलीसेढ़",
    slug: "alwar-siliserh",
    hindi_name: "अलवर और सिलीसेढ़",
    state: "Rajasthan",
    region: "Mewat & Aravalli Hills",
    category: "Heritage Lake Palace",
    tagline: "Historic 19th-century royal lake palace, tranquil waters, and Aravalli mountain reflections.",
    subtitle_en: "Historic 19th-century royal lake palace, tranquil waters, and Aravalli mountain reflections.",
    subtitle_hi: "सिलीसेढ़ लेक पैलेस, अरावली पर्वतमाला और ऐतिहासिक अलवर नगर।",
    description: "Surrounded by the dense Aravalli mountain hills, Siliserh Lake Palace was built in 1845 as a royal hunting lodge, offering boat rides and serene mountain vistas.",
    description_en: "Surrounded by the dense Aravalli mountain hills, Siliserh Lake Palace was built in 1845 as a royal hunting lodge, offering boat rides and serene mountain vistas.",
    description_hi: "1845 में निर्मित ऐतिहासिक सिलीसेढ़ झील महल अरावली की वादियों के बीच बोटिंग और शांत प्रकृति का अनुभव कराता है।",
    hero_image: "/images/destinations/alwar-siliserh/hero.jpg",
    hero_artwork: "/artworks/alwar-siliserh.jpg",
    hero_photo: "/images/destinations/alwar-siliserh/hero.jpg",
    latitude: 27.5342,
    longitude: 76.5411,
    altitude_meters: 270,
    best_time_to_visit: "October to March",
    weather_type: "Pleasant Hill Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-sariska-bhangarh",
    name: "Sariska & Bhangarh",
    name_en: "Sariska & Bhangarh",
    name_hi: "सरिस्का और भानगढ़",
    slug: "sariska-bhangarh",
    hindi_name: "सरिस्का और भानगढ़",
    state: "Rajasthan",
    region: "Aravalli Wilderness",
    category: "Wildlife & Historic Ruins",
    tagline: "Dense dry deciduous forest wildlife, tiger territory, and legendary ancient stone ruins of Bhangarh.",
    subtitle_en: "Dense dry deciduous forest wildlife, tiger territory, and legendary ancient stone ruins of Bhangarh.",
    subtitle_hi: "सरिस्का के वन्य जीव और अरावली की तलहटी में भानगढ़ के ऐतिहासिक खंडहर।",
    description: "Combines the thrill of tiger safari in Sariska National Park with the architectural mystery and scenic stone ramparts of the 17th-century Bhangarh Fort ruins.",
    description_en: "Combines the thrill of tiger safari in Sariska National Park with the architectural mystery and scenic stone ramparts of the 17th-century Bhangarh Fort ruins.",
    description_hi: "सरिस्का के घने जंगलों की सफारी और 17वीं सदी के रहस्यमयी भानगढ़ किले के ऐतिहासिक पत्थरों की खोज।",
    hero_image: "/images/destinations/sariska-bhangarh/hero.jpg",
    hero_artwork: "/artworks/sariska-bhangarh.jpg",
    hero_photo: "/images/destinations/sariska-bhangarh/hero.jpg",
    latitude: 27.3292,
    longitude: 76.4389,
    altitude_meters: 420,
    best_time_to_visit: "October to April",
    weather_type: "Dry Forest Air",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-dehradun",
    name: "Dehradun (Rajpur Road)",
    name_en: "Dehradun",
    name_hi: "देहरादून",
    slug: "dehradun",
    hindi_name: "देहरादून",
    state: "Uttarakhand",
    region: "Doon Valley Foothills",
    category: "Valley Cafés & Foothills",
    tagline: "Sal-forested foothills, historic Rajpur Road bakeries, and cool Himalayan mountain streams.",
    subtitle_en: "Sal-forested foothills, historic Rajpur Road bakeries, and cool Himalayan mountain streams.",
    subtitle_hi: "साल के घने जंगल, राजपुर रोड के प्रसिद्ध कैफ़े और दून घाटी की ठंडी हवा।",
    description: "Nestled in the Doon Valley between the Ganga and Yamuna, Dehradun offers historic bakery trails along Rajpur Road, Robber's Cave, and gateway paths to Mussoorie.",
    description_en: "Nestled in the Doon Valley between the Ganga and Yamuna, Dehradun offers historic bakery trails along Rajpur Road, Robber's Cave, and gateway paths to Mussoorie.",
    description_hi: "गंगा और यमुना के बीच बसी दून घाटी, जो अपने शांत कैफ़े, साल वनों और मसूरी की ओर जाती घुमावदार सड़कों के लिए जानी जाती है।",
    hero_image: "/images/destinations/dehradun/hero.jpg",
    hero_artwork: "/artworks/dehradun.jpg",
    hero_photo: "/images/destinations/dehradun/hero.jpg",
    latitude: 30.3165,
    longitude: 78.0322,
    altitude_meters: 640,
    best_time_to_visit: "Round the Year",
    weather_type: "Pleasant Valley Mist",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-chandigarh",
    name: "Chandigarh",
    name_en: "Chandigarh",
    name_hi: "चंडीगढ़",
    slug: "chandigarh",
    hindi_name: "चंडीगढ़",
    state: "Punjab / Haryana",
    region: "Shivalik Plains",
    category: "Modernist Architecture & Lakes",
    tagline: "Sukhna Lake morning reflections, Nek Chand's Rock Garden, and tree-lined modernist boulevards.",
    subtitle_en: "Sukhna Lake morning reflections, Nek Chand's Rock Garden, and tree-lined modernist boulevards.",
    subtitle_hi: "सुखना झील की शांति, रॉक गार्डन का अनोखा शिल्प और चौड़ी हरी-भरी सड़कें।",
    description: "Designed by Le Corbusier at the base of the Shivalik hills, Chandigarh is celebrated for its modernist urban planning, Sukhna Lake sunsets, and the iconic Rock Garden.",
    description_en: "Designed by Le Corbusier at the base of the Shivalik hills, Chandigarh is celebrated for its modernist urban planning, Sukhna Lake sunsets, and the iconic Rock Garden.",
    description_hi: "शिवालिक की तलहटी में बसा आधुनिक शहर, जो अपनी वास्तुकला, सुखना झील और रॉक गार्डन के लिए देश-विदेश में प्रसिद्ध है।",
    hero_image: "/images/destinations/chandigarh/hero.jpg",
    hero_artwork: "/artworks/chandigarh.jpg",
    hero_photo: "/images/destinations/chandigarh/hero.jpg",
    latitude: 30.7333,
    longitude: 76.7794,
    altitude_meters: 321,
    best_time_to_visit: "October to March",
    weather_type: "Crisp Pleasant Air",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-morni-hills",
    name: "Morni Hills",
    name_en: "Morni Hills",
    name_hi: "मोरनी हिल्स",
    slug: "morni-hills",
    hindi_name: "मोरनी हिल्स",
    state: "Haryana",
    region: "Shivalik Hills",
    category: "Pine Slopes & Twin Lakes",
    tagline: "Pine-covered Shivalik mountain ridges, peaceful Tikkar Taal lake, and quiet hill roads.",
    subtitle_en: "Pine-covered Shivalik mountain ridges, peaceful Tikkar Taal lake, and quiet hill roads.",
    subtitle_hi: "चीड़ के जंगलों से घिरी शिवालिक की पहाड़ियाँ और टिक्कर ताल झील की सुंदरता।",
    description: "Haryana's only hill station, nestled in the Shivalik ranges, featuring the sacred twin lakes of Tikkar Taal, pine forests, and scenic viewpoints.",
    description_en: "Haryana's only hill station, nestled in the Shivalik ranges, featuring the sacred twin lakes of Tikkar Taal, pine forests, and scenic viewpoints.",
    description_hi: "हरियाणा का एकमात्र हिल स्टेशन, जहाँ चीड़ के घने जंगल और टिक्कर ताल झील शांत पहाड़ी अनुभव प्रदान करते हैं।",
    hero_image: "/images/destinations/morni-hills/hero.jpg",
    hero_artwork: "/artworks/morni-hills.jpg",
    hero_photo: "/images/destinations/morni-hills/hero.jpg",
    latitude: 30.6908,
    longitude: 77.0869,
    altitude_meters: 1220,
    best_time_to_visit: "September to April",
    weather_type: "Cool Mountain Air",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-lansdowne",
    name: "Lansdowne",
    name_en: "Lansdowne",
    name_hi: "लैंसडाउन",
    slug: "lansdowne",
    hindi_name: "लैंसडाउन",
    state: "Uttarakhand",
    region: "Garhwal Hills",
    category: "Cantonment & Pine Ridge",
    tagline: "Quiet oak and blue pine ridge walks, colonial stone churches, and snow-peak panoramas.",
    subtitle_en: "Quiet oak and blue pine ridge walks, colonial stone churches, and snow-peak panoramas.",
    subtitle_hi: "ओक और चीड़ के शांत जंगल, ऐतिहासिक पत्थर के चर्च और हिमालय का विहंगम दृश्य।",
    description: "An unspoilt Garhwal cantonment town founded in 1887, surrounded by dense blue pine forests with serene walking trails to Tip-in-Top and Bhulla Tal.",
    description_en: "An unspoilt Garhwal cantonment town founded in 1887, surrounded by dense blue pine forests with serene walking trails to Tip-in-Top and Bhulla Tal.",
    description_hi: "गढ़वाल की पहाड़ियों में बसा शांत कैंटोनमेंट, जहाँ चीड़ के वनों में सुकून भरी सैर और टिप-इन-टॉप से हिमालय के दृश्य मिलते हैं।",
    hero_image: "/images/destinations/lansdowne/hero.jpg",
    hero_artwork: "/artworks/lansdowne.jpg",
    hero_photo: "/images/destinations/lansdowne/hero.jpg",
    latitude: 29.8377,
    longitude: 78.6872,
    altitude_meters: 1706,
    best_time_to_visit: "Round the Year",
    weather_type: "Crisp Pine Breeze",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-mussoorie",
    name: "Mussoorie",
    name_en: "Mussoorie",
    name_hi: "मसूरी",
    slug: "mussoorie",
    hindi_name: "मसूरी",
    state: "Uttarakhand",
    region: "Garhwal Hills",
    category: "Colonial Hill Station",
    tagline: "Queen of the Hills, colonial bookshops, winterline sunsets, and oak trails.",
    subtitle_en: "Queen of the Hills, colonial bookshops, winterline sunsets, and oak trails.",
    subtitle_hi: "पहाड़ों की रानी, विंटरलाइन सूर्यास्त और लैंडौर की ऐतिहासिक गलियाँ।",
    description: "Perched on a horseshoe ridge overlooking the Doon Valley, offering tranquil walks along Camel's Back Road and historic bakeries in Landour.",
    description_en: "Perched on a horseshoe ridge overlooking the Doon Valley, offering tranquil walks along Camel's Back Road and historic bakeries in Landour.",
    description_hi: "दून घाटी के ऊपर स्थित मसूरी अपने लैंडौर के शांत रास्तों, विंटरलाइन सूर्यास्त और पुरानी बेकरियों के लिए जाना जाता है।",
    hero_image: "/images/destinations/mussoorie/hero.jpg",
    hero_artwork: "/artworks/mussoorie.jpg",
    hero_photo: "/images/destinations/mussoorie/hero.jpg",
    latitude: 30.4598,
    longitude: 78.0644,
    altitude_meters: 2005,
    best_time_to_visit: "March to June & Sept to Nov",
    weather_type: "Cool Mountain Mist",
    one_day_available: true,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-udaipur",
    name: "Udaipur",
    name_en: "Udaipur",
    name_hi: "उदयपुर",
    slug: "udaipur",
    hindi_name: "उदयपुर",
    state: "Rajasthan",
    region: "Mewar Lakes",
    category: "Lakes & White Palaces",
    tagline: "Shimmering lake waters, whitewashed palaces, and romantic rooftop evenings.",
    subtitle_en: "Shimmering lake waters, whitewashed palaces, and romantic rooftop evenings.",
    subtitle_hi: "पिछोला झील की लहरें, श्वेत संगमरमर के महल और शाही मेवाड़ी संस्कृति।",
    description: "The City of Lakes framed by the Aravalli Hills, offering tranquil boat rides on Lake Pichola and authentic Mewari hospitality.",
    description_en: "The City of Lakes framed by the Aravalli Hills, offering tranquil boat rides on Lake Pichola and authentic Mewari hospitality.",
    description_hi: "अरावली पहाड़ियों से घिरा झीलों का शहर, जहाँ पिछोला झील पर नाव की सवारी और सिटी पैलेस का वैभव मन मोह लेता है।",
    hero_image: "/images/destinations/udaipur/hero.jpg",
    hero_artwork: "/artworks/udaipur.jpg",
    hero_photo: "/images/destinations/udaipur/hero.jpg",
    latitude: 24.5854,
    longitude: 73.7125,
    altitude_meters: 598,
    best_time_to_visit: "September to March",
    weather_type: "Pleasant Lake Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-varanasi",
    name: "Varanasi",
    name_en: "Varanasi",
    name_hi: "वाराणसी",
    slug: "varanasi",
    hindi_name: "वाराणसी",
    state: "Uttar Pradesh",
    region: "Ganga Riverfront",
    category: "Eternal Ghats & Silk Lanes",
    tagline: "Ancient eternal ghats, dawn boat reflections, sacred chanting, and silk lanes.",
    subtitle_en: "Ancient eternal ghats, dawn boat reflections, sacred chanting, and silk lanes.",
    subtitle_hi: "काशी के पावन घाट, भोर की नौका सवारी और गंगा आरती का दिव्य अनुभव।",
    description: "One of the oldest continuously inhabited cities on earth, where life, philosophy, and spiritual devotion revolve around the sacred Ganges.",
    description_en: "One of the oldest continuously inhabited cities on earth, where life, philosophy, and spiritual devotion revolve around the sacred Ganges.",
    description_hi: "संसार की सबसे प्राचीन नगरी, जहाँ दशाश्वमेध और अस्सी घाट पर जीवन, दर्शन और गंगा आरती का अद्भुत संगम देखने को मिलता है।",
    hero_image: "/images/destinations/varanasi/hero.jpg",
    hero_artwork: "/images/destinations/varanasi/illustration.jpg",
    hero_photo: "/images/destinations/varanasi/hero.jpg",
    latitude: 25.3176,
    longitude: 82.9739,
    altitude_meters: 80,
    best_time_to_visit: "October to March",
    weather_type: "Ancient River Breeze",
    one_day_available: true,
    trek_available: false,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-leh",
    name: "Leh",
    name_en: "Leh",
    name_hi: "लेह",
    slug: "leh",
    hindi_name: "लेह",
    state: "Ladakh",
    region: "Trans-Himalayan Cold Desert",
    category: "High Altitude Passes & Gompas",
    tagline: "Barren moonscapes, thousand-year-old gompas, and world-highest motorable passes.",
    subtitle_en: "Barren moonscapes, thousand-year-old gompas, and world-highest motorable passes.",
    subtitle_hi: "लद्दाख के विहंगम मरुस्थल, प्राचीन बौद्ध मठ और विश्व के सबसे ऊँचे दर्रे।",
    description: "The crown of Ladakh situated in the Indus River Valley, where stark dramatic mountain terrain meets ancient Tibetan Buddhist culture.",
    description_en: "The crown of Ladakh situated in the Indus River Valley, where stark dramatic mountain terrain meets ancient Tibetan Buddhist culture.",
    description_hi: "सिंधु नदी घाटी में स्थित लद्दाख का हृदय, जहाँ प्राचीन थिकसे व हेमिस मठ और खारदुंग ला जैसे ऊँचे दर्रे स्थित हैं।",
    hero_image: "/images/destinations/leh/hero.jpg",
    hero_artwork: "/artworks/fallback_himalayan.jpg",
    hero_photo: "/images/destinations/leh/hero.jpg",
    latitude: 34.1526,
    longitude: 77.5771,
    altitude_meters: 3500,
    best_time_to_visit: "May to October",
    weather_type: "High Altitude Crisp Air",
    one_day_available: false,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-spiti",
    name: "Spiti Valley",
    name_en: "Spiti Valley",
    name_hi: "स्पीति घाटी",
    slug: "spiti",
    hindi_name: "स्पीति घाटी",
    state: "Himachal Pradesh",
    region: "Cold Desert Valley",
    category: "Cold Desert Monasteries",
    tagline: "The middle land between Tibet and India, cliffside monasteries, and fossil villages.",
    subtitle_en: "The middle land between Tibet and India, cliffside monasteries, and fossil villages.",
    subtitle_hi: "तिब्बत और भारत के बीच का मध्य देश, की गोम्पा और जीवाश्मों के गाँव।",
    description: "A high-altitude desert wonderland carved by the Spiti River, renowned for century-old gompas like Key and Dhankar, and pristine high-altitude lakes.",
    description_en: "A high-altitude desert wonderland carved by the Spiti River, renowned for century-old gompas like Key and Dhankar, and pristine high-altitude lakes.",
    description_hi: "स्पीति नदी द्वारा तराशी गई शीत मरुस्थल घाटी, जहाँ 1000 वर्ष पुराना की मठ और चंद्रताल झील स्थित हैं।",
    hero_image: "/images/destinations/spiti-valley/hero.jpg",
    hero_artwork: "/artworks/fallback_desert.jpg",
    hero_photo: "/images/destinations/spiti-valley/hero.jpg",
    latitude: 32.2461,
    longitude: 78.0349,
    altitude_meters: 3800,
    best_time_to_visit: "June to October",
    weather_type: "Dry Cold Moonscape",
    one_day_available: false,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
  {
    id: "dest-munnar",
    name: "Munnar",
    name_en: "Munnar",
    name_hi: "मुन्नार",
    slug: "munnar",
    hindi_name: "मुन्नार",
    state: "Kerala",
    region: "Western Ghats Tea Hills",
    category: "Tea Plantations & Misty Gaps",
    tagline: "Rolling emerald tea plantations, misty mountain gaps, and cardamom forests.",
    subtitle_en: "Rolling emerald tea plantations, misty mountain gaps, and cardamom forests.",
    subtitle_hi: "मखमली चाय के बागान, धुंध भरी पहाड़ियाँ और इलायची के महकते जंगल।",
    description: "Perched at the confluence of three mountain streams in the Western Ghats, Munnar offers endless green tea slopes, cool breezes, and colonial bungalows.",
    description_en: "Perched at the confluence of three mountain streams in the Western Ghats, Munnar offers endless green tea slopes, cool breezes, and colonial bungalows.",
    description_hi: "पश्चिमी घाट की वादियों में स्थित मुन्नार हरी-भरी चाय की ढलानों, शीतल बयार और अनामुडी चोटी के लिए प्रसिद्ध है।",
    hero_image: "/images/destinations/fallbacks/valley.jpg",
    hero_artwork: "/artworks/fallback_valley.jpg",
    hero_photo: "/images/destinations/fallbacks/valley.jpg",
    latitude: 10.0889,
    longitude: 77.0595,
    altitude_meters: 1600,
    best_time_to_visit: "September to May",
    weather_type: "Misty Green Slopes",
    one_day_available: false,
    trek_available: true,
    nearby_available: true,
    is_featured: true,
    is_curated: true,
  },
];

export const CANONICAL_HINDI_NAMES: Record<string, string> = {
  manali: "मनाली",
  rishikesh: "ऋषिकेश",
  kasol: "कसोल",
  dharamshala: "धर्मशाला",
  "dharamshala & mcleod ganj": "धर्मशाला",
  mcleodganj: "मैक्लोडगंज",
  goa: "गोवा",
  jaipur: "जयपुर",
  mussoorie: "मसूरी",
  udaipur: "उदयपुर",
  varanasi: "वाराणसी",
  leh: "लेह",
  "leh ladakh": "लेह",
  ladakh: "लद्दाख",
  spiti: "स्पीति घाटी",
  "spiti valley": "स्पीति घाटी",
  "spiti-valley": "स्पीति घाटी",
  munnar: "मुन्नार",
  "tungnath-chandrashila": "तुंगनाथ–चंद्रशिला",
  "tungnath–chandrashila": "तुंगनाथ–चंद्रशिला",
  "tungnath-chandrashila trek": "तुंगनाथ–चंद्रशिला",
  "tungnath–chandrashila trek": "तुंगनाथ–चंद्रशिला",
  tungnath: "तुंगनाथ–चंद्रशिला",
  tunganath: "तुंगनाथ–चंद्रशिला",
  "tungnath temple": "तुंगनाथ–चंद्रशिला",
  chandrashila: "तुंगनाथ–चंद्रशिला",
  "chandrashila peak": "तुंगनाथ–चंद्रशिला",
  "chandrashila summit": "तुंगनाथ–चंद्रशिला",
  "tungnath chandrashila": "तुंगनाथ–चंद्रशिला",
  "chopta tungnath chandrashila": "तुंगनाथ–चंद्रशिला",
  chopta: "तुंगनाथ–चंद्रशिला",
  delhi: "दिल्ली",
  pune: "पुणे",
  kolkata: "कोलकाता",
  ayodhya: "अयोध्या",
  mumbai: "मुंबई",
  bengaluru: "बेंगलुरु",
  chennai: "चेन्नई",
  kochi: "कोच्चि",
  agra: "आगरा",
  amritsar: "अमृतसर",
  lucknow: "लखनऊ",
  gokarna: "गोकर्ण",
  "kainchi-dham": "कैंची धाम",
  "kainchi dham": "कैंची धाम",
  kainchi: "कैंची धाम",
  "neem karoli baba ashram": "नीम करौली बाबा आश्रम",
  murthal: "मुरथल",
  "mathura-vrindavan": "मथुरा और वृन्दावन",
  mathura: "मथुरा",
  vrindavan: "वृन्दावन",
  "haridwar-rishikesh": "हरिद्वार और ऋषिकेश",
  haridwar: "हरिद्वार",
  "damdama-sohna": "दमदमा और सोहना",
  damdama: "दमदमा झील",
  sohna: "सोहना",
  neemrana: "नीमराना",
  "alwar-siliserh": "अलवर और सिलीसेढ़",
  alwar: "अलवर",
  siliserh: "सिलीसेढ़",
  "sariska-bhangarh": "सरिस्का और भानगढ़",
  sariska: "सरिस्का",
  bhangarh: "भानगढ़",
  dehradun: "देहरादून",
  chandigarh: "चंडीगढ़",
  "morni-hills": "मोरनी हिल्स",
  morni: "मोरनी हिल्स",
  lansdowne: "लैंसडाउन",
};

/**
 * Returns canonical Hindi name for any destination slug or name
 */
export function getCanonicalHindiName(slugOrName?: string | null): string {
  if (!slugOrName) return "";
  const cleaned = slugOrName
    .toLowerCase()
    .replace(/^(dyn|dest)-/, "")
    .trim();
  return CANONICAL_HINDI_NAMES[cleaned] || "";
}

/**
 * Resolves a destination by slug or ID against canonical registry
 */
export function findCanonicalDestination(slugOrId?: string | null): CanonicalDestination | undefined {
  if (!slugOrId) return undefined;
  const cleaned = slugOrId
    .toLowerCase()
    .replace(/^(dyn|dest)-/, "")
    .trim();
  return CANONICAL_DESTINATIONS.find(
    (d) =>
      d.slug.toLowerCase() === cleaned ||
      d.id.toLowerCase() === `dest-${cleaned}` ||
      d.name.toLowerCase() === cleaned
  );
}
