/**
 * VANVAS Destination Content Model
 * Centralized, structured data layer for Trek Expeditions, One-Day Round Trips,
 * and Destination Logistics across all Indian sanctuaries.
 */

export interface DestinationWaypoint {
  id: string;
  name: string;
  hindiName: string;
  elevation: string;
  distance: string;
  timeFromPrev: string;
  difficulty: string;
  latitude: number;
  longitude: number;
  description: string;
  imageUrl: string;
}

export interface DestinationTrekInfo {
  hasTrek: boolean;
  title: string;
  hindiTitle: string;
  trailSummary: string;
  baseCamp: string;
  elevationGain: string;
  peakAltitude: string;
  distance: string;
  duration: string;
  difficulty: "Easy" | "Moderate" | "Challenging" | "Alpine / Demanding";
  bestSeason: string;
  approachTransport: string;
  packingChecklist: string[];
  waypoints: DestinationWaypoint[];
  nonTrekNotice?: {
    heading: string;
    explanation: string;
    alternativeMode: string;
  };
}

export interface DayTripBlock {
  time: string;
  period: "DAWN" | "MORNING" | "MIDDAY" | "AFTERNOON" | "SUNSET" | "NIGHT";
  title: string;
  hindiTitle: string;
  activity: string;
  location: string;
  highlight: string;
  duration: string;
  tips: string;
  iconType: "sunrise" | "landmark" | "food" | "nature" | "sunset" | "night" | "tea";
}

export interface DestinationDayTrip {
  title: string;
  hindiTitle: string;
  tagline: string;
  estimatedHours: string;
  transitContext: string;
  totalDistance: string;
  blocks: DayTripBlock[];
}

export const DESTINATION_TREK_REGISTRY: Record<string, DestinationTrekInfo> = {
  "tungnath-chandrashila": {
    hasTrek: true,
    title: "Chopta → Tungnath Temple → Chandrashila Summit",
    hindiTitle: "चोपता → तुंगनाथ मंदिर → चंद्रशिला शिखर",
    trailSummary: "Ascend from Chopta meadows (2,680m) to the world's highest Shiva shrine (3,680m), then conquer the 4,000m Chandrashila summit for an unrivaled 360° Chaukhamba sunrise vista.",
    baseCamp: "Chopta Bugyals (2,680 m)",
    elevationGain: "+1,320 m",
    peakAltitude: "4,000 m (13,123 ft)",
    distance: "5.0 km one-way (10 km round trip)",
    duration: "4.5 – 6 Hours total",
    difficulty: "Moderate",
    bestSeason: "April to November (Shrine open); Winter Snow Trek (Dec–Feb)",
    approachTransport: "Road access to Chopta base from Rishikesh/Haridwar via Rudraprayag & Ukhimath. Strictly walking/ponies only beyond Chopta trailhead.",
    packingChecklist: ["Sturdy ankle-grip hiking boots", "Wind & waterproof shell", "Fleece layer", "Trekking pole", "Water bottle & cash (No ATMs at Chopta)"],
    waypoints: [
      {
        id: "chopta",
        name: "Chopta Meadows (Base Camp)",
        hindiName: "चोपता बुग्याल (आधार शिविर)",
        elevation: "2,680 m",
        distance: "0 km (Starting point)",
        timeFromPrev: "Start",
        difficulty: "Easy / Meadow",
        latitude: 30.4850,
        longitude: 79.1790,
        description: "Lush alpine meadows (bugyals) bordered by dense deodar, oak, and rhododendron forests. Base roadhead with rustic tea stalls and eco campsites.",
        imageUrl: "/images/places/tungnath-chandrashila/chopta-meadows.jpg",
      },
      {
        id: "tungnath",
        name: "Tungnath Temple (Panch Kedar)",
        hindiName: "तुंगनाथ मंदिर (तृतीय केदार)",
        elevation: "3,680 m",
        distance: "3.5 km from Chopta",
        timeFromPrev: "2.5 – 3.5 hrs ascent",
        difficulty: "Moderate stone paved uphill",
        latitude: 30.4886,
        longitude: 79.2173,
        description: "World's highest Shiva temple and the 3rd Panch Kedar. Ancient North Indian Nagara stone architecture standing on an alpine ridge for over a millennium.",
        imageUrl: "/images/places/tungnath-chandrashila/tungnath-temple.jpg",
      },
      {
        id: "chandrashila",
        name: "Chandrashila Summit (Moon Rock)",
        hindiName: "चंद्रशिला शिखर (4,000 मी)",
        elevation: "4,000 m",
        distance: "1.5 km beyond Temple",
        timeFromPrev: "1 – 1.5 hrs from Temple",
        difficulty: "Steep rocky crag ascent",
        latitude: 30.4930,
        longitude: 79.2185,
        description: "Unrivalled 360-degree panoramic sunrise vista towering in front of the colossal Chaukhamba massif, Nanda Devi, Trishul, and Kedarnath peaks.",
        imageUrl: "/images/places/tungnath-chandrashila/chandrashila-summit.jpg",
      },
    ],
  },
  manali: {
    hasTrek: true,
    title: "Jogini Waterfall & Solang Valley Alpine Pass Trail",
    hindiTitle: "जोगिनी जलप्रपात एवं सोलांग घाटी अल्पाइन मार्ग",
    trailSummary: "Forest walk through ancient deodar canopies from Vashisht village up to cascading Jogini waterfalls, continuing toward Solang Valley alpine pine trails.",
    baseCamp: "Vashisht Village / Old Manali (2,050 m)",
    elevationGain: "+750 m",
    peakAltitude: "2,800 m",
    distance: "6.5 km one-way",
    duration: "3.5 – 5 Hours",
    difficulty: "Moderate",
    bestSeason: "March to June & September to November",
    approachTransport: "Auto-rickshaws or walking from Manali Mall Road to Vashisht temple trailhead. Return via local Solang-Manali bus.",
    packingChecklist: ["Trail walking shoes", "Light fleece", "Rain poncho", "Water bottle", "Sun protection"],
    waypoints: [
      {
        id: "vashisht",
        name: "Vashisht Temple & Hot Springs (Trailhead)",
        hindiName: "वशिष्ठ मंदिर एवं गर्म जल कुंड",
        elevation: "2,050 m",
        distance: "0 km",
        timeFromPrev: "Start",
        difficulty: "Easy",
        latitude: 32.2612,
        longitude: 77.1873,
        description: "Ancient stone-carved temple with natural sulfur hot spring baths and traditional wooden houses.",
        imageUrl: "/images/places/manali/hadimba-temple.webp",
      },
      {
        id: "jogini",
        name: "Jogini Waterfalls Upper Tier",
        hindiName: "जोगिनी जलप्रपात",
        elevation: "2,400 m",
        distance: "3.5 km",
        timeFromPrev: "1.5 hrs",
        difficulty: "Moderate uphill dirt path",
        latitude: 32.2700,
        longitude: 77.1890,
        description: "Dramatic cascade tumbling down sheer granite cliffs framed by pine trees with sweeping views of the Beas river basin.",
        imageUrl: "/images/places/manali/jogini-waterfall.webp",
      },
      {
        id: "solang-ridge",
        name: "Solang Alpine Ridge Point",
        hindiName: "सोलांग अल्पाइन रिज",
        elevation: "2,800 m",
        distance: "3.0 km further",
        timeFromPrev: "1.5 hrs",
        difficulty: "Moderate",
        latitude: 32.3167,
        longitude: 77.1500,
        description: "Open alpine slopes overlooking snow-clad Pir Panjal summits and valley paragliding zones.",
        imageUrl: "/images/places/manali/solang-valley.webp",
      },
    ],
  },
  kasol: {
    hasTrek: true,
    title: "Chalal Riverside Trail & Kheerganga Thermal Springs",
    hindiTitle: "छलाल नदी मार्ग एवं खीरगंगा गर्म कुंड",
    trailSummary: "Follow roaring Parvati River through deodar woods to bohemian Chalal, connecting onward to Barshaini and the sacred natural hot sulfur springs of Kheerganga.",
    baseCamp: "Kasol Market / Barshaini Roadhead (1,580 m – 2,195 m)",
    elevationGain: "+960 m",
    peakAltitude: "2,960 m",
    distance: "12 km from Barshaini",
    duration: "5 – 6.5 Hours",
    difficulty: "Moderate",
    bestSeason: "April to June & September to November",
    approachTransport: "Local HRTC buses and shared cabs from Bhuntar to Kasol & Barshaini. Walking only beyond Barshaini bridge.",
    packingChecklist: ["Ankle-support trekking shoes", "Warm thermals", "Towel for hot spring", "Headlamp", "Cash"],
    waypoints: [
      {
        id: "chalal",
        name: "Chalal Pine & River Suspension Bridge",
        hindiName: "छलाल पाइन वन एवं झूला पुल",
        elevation: "1,600 m",
        distance: "1.5 km from Kasol",
        timeFromPrev: "30 mins",
        difficulty: "Easy riverbank path",
        latitude: 32.0120,
        longitude: 77.3200,
        description: "Pristine pine trail along rushing glacial Parvati water leading to quiet wooden hamlet cafes.",
        imageUrl: "/images/places/kasol/chalal-trail.webp",
      },
      {
        id: "nakthan",
        name: "Nakthan Traditional Village",
        hindiName: "नक्तन पारंपरिक गाँव",
        elevation: "2,300 m",
        distance: "4.5 km from Barshaini",
        timeFromPrev: "2 hrs",
        difficulty: "Moderate uphill",
        latitude: 31.9800,
        longitude: 77.4200,
        description: "Ancient wooden architectural hamlet with apple orchards and mountain dhabas serving hot chai.",
        imageUrl: "/images/places/kasol/tosh-village.webp",
      },
      {
        id: "kheerganga",
        name: "Kheerganga Summit & Sacred Hot Spring",
        hindiName: "खीरगंगा शिखर एवं प्राकृतिक गर्म कुंड",
        elevation: "2,960 m",
        distance: "7.5 km from Nakthan",
        timeFromPrev: "3 hrs",
        difficulty: "Moderate / Forest ascent",
        latitude: 31.9900,
        longitude: 77.5100,
        description: "Natural volcanic sulfur bath overlooking snow-capped Himalayan peaks and starry alpine skies.",
        imageUrl: "/images/places/kasol/kheerganga-trek.webp",
      },
    ],
  },
  dharamshala: {
    hasTrek: true,
    title: "Triund Ridge Panoramic Dhauladhar Trail",
    hindiTitle: "त्रिउंड रिज धौलाधार पदयात्रा",
    trailSummary: "The crown jewel trek of Dharamshala ascending through oak and rhododendron forests from Dharamkot/Galu Temple to the dramatic Triund ridge towering beneath Dhauladhar peaks.",
    baseCamp: "Dharamkot / Galu Devi Temple (2,100 m)",
    elevationGain: "+775 m",
    peakAltitude: "2,875 m",
    distance: "9.0 km round trip",
    duration: "4 – 5.5 Hours total",
    difficulty: "Moderate",
    bestSeason: "March to June & September to December",
    approachTransport: "Taxis/walking from McLeod Ganj to Galu Devi Temple trailhead. Walking strictly beyond Galu.",
    packingChecklist: ["Grippy trail shoes", "Windbreaker", "1.5L water", "Sun hat", "Cash for chai shops"],
    waypoints: [
      {
        id: "galu",
        name: "Galu Devi Temple (Trailhead)",
        hindiName: "गालू देवी मंदिर (आरंभ बिंदु)",
        elevation: "2,130 m",
        distance: "0 km",
        timeFromPrev: "Start",
        difficulty: "Easy",
        latitude: 32.2530,
        longitude: 76.3260,
        description: "Trail registration point nestled in dense rhododendron forest with panoramic Kangra valley views.",
        imageUrl: "/images/places/dharamshala/tsuglagkhang-complex.webp",
      },
      {
        id: "magic-view",
        name: "Magic View Tea Shop (Halfway Point)",
        hindiName: "मैजिक व्यू चाय केंद्र",
        elevation: "2,500 m",
        distance: "2.5 km",
        timeFromPrev: "1.5 hrs",
        difficulty: "Moderate stone path",
        latitude: 32.2610,
        longitude: 76.3350,
        description: "Oldest mountain tea stall in the valley with cliffside seating and ginger lemon honey tea.",
        imageUrl: "/images/places/dharamshala/bhagsu-waterfall.webp",
      },
      {
        id: "triund-top",
        name: "Triund Ridge (2,875 m)",
        hindiName: "त्रिउंड रिज शिखर",
        elevation: "2,875 m",
        distance: "2.0 km steep ascent",
        timeFromPrev: "1.5 hrs",
        difficulty: "22-curve stone ascent",
        latitude: 32.2700,
        longitude: 76.3450,
        description: "Massive open grassy ridge with colossal Dhauladhar granite wall towering directly in front and Kangra Valley below.",
        imageUrl: "/images/places/dharamshala/triund-trek.webp",
      },
    ],
  },
  rishikesh: {
    hasTrek: true,
    title: "Neer Garh Waterfall & Kunjapuri Sunrise Ridge",
    hindiTitle: "नीर गढ़ जलप्रपात एवं कुंजापुरी सूर्योदय रिज",
    trailSummary: "Ascend jungle trails through cascading limestone natural pools at Neer Garh, continuing up to the Kunjapuri Devi temple ridge for 360° views of the Greater Himalayas and Ganga bend.",
    baseCamp: "Tapovan / Neer Bridge (372 m)",
    elevationGain: "+1,270 m",
    peakAltitude: "1,645 m",
    distance: "7.0 km combined trail",
    duration: "3 – 4.5 Hours",
    difficulty: "Moderate",
    bestSeason: "October to April",
    approachTransport: "Scooter or shared taxi from Tapovan to Neer Garh entrance. Early morning taxi for Kunjapuri sunrise.",
    packingChecklist: ["Breathable sports shoes", "Quick-dry clothes", "Camera", "Sunscreen", "Water bottle"],
    waypoints: [
      {
        id: "neer-lower",
        name: "Neer Garh Lower Limestone Cascade",
        hindiName: "नीर गढ़ निचला झरना",
        elevation: "450 m",
        distance: "1.0 km from road",
        timeFromPrev: "25 mins",
        difficulty: "Easy forest path",
        latitude: 30.1380,
        longitude: 78.3360,
        description: "Turquoise mountain water tumbling over limestone shelves creating refreshing natural swimming plunge pools.",
        imageUrl: "/images/places/rishikesh/neer-garh-waterfall.webp",
      },
      {
        id: "neer-upper",
        name: "Neer Garh Upper Tier & Forest Canopy",
        hindiName: "नीर गढ़ ऊपरी जलप्रपात",
        elevation: "650 m",
        distance: "1.5 km uphill",
        timeFromPrev: "45 mins",
        difficulty: "Moderate rocky path",
        latitude: 30.1450,
        longitude: 78.3410,
        description: "Secluded multi-tiered waterfall nestled inside dense subtropical jungle with mountain chai stands.",
        imageUrl: "/images/places/rishikesh/triveni-ghat.webp",
      },
      {
        id: "kunjapuri",
        name: "Kunjapuri Devi Temple Summit (1,645 m)",
        hindiName: "कुंजापुरी देवी मंदिर शिखर",
        elevation: "1,645 m",
        distance: "Ridge trek / scenic drive",
        timeFromPrev: "1.5 hrs",
        difficulty: "Moderate stairs to summit",
        latitude: 30.1800,
        longitude: 78.3100,
        description: "Sacred Shakti Peeth with dramatic 360° panorama of Swargarohini, Chaukhamba, and the sparkling silver curve of the Ganga.",
        imageUrl: "/images/places/rishikesh/beatles-ashram.webp",
      },
    ],
  },
  mussoorie: {
    hasTrek: true,
    title: "Landour Oak Forest Loop & George Everest Ridge Trail",
    hindiTitle: "लैंडौर बाँज वन लूप एवं जॉर्ज एवरेस्ट रिज मार्ग",
    trailSummary: "Gentle heritage trail weaving through serene Himalayan cedar, oak and rhododendron canopies in Landour Cantonment and the high ridge of Sir George Everest Estate.",
    baseCamp: "Picture Palace / Library Chowk (2,005 m)",
    elevationGain: "+250 m",
    peakAltitude: "2,250 m",
    distance: "8.0 km loop",
    duration: "3 – 4 Hours",
    difficulty: "Easy",
    bestSeason: "Year-round (Autumn & Winter for winterline glow)",
    approachTransport: "Pedestrian-friendly walking paths in Landour; shared cycle rickshaws/taxis from Mall Road to Hathipaon.",
    packingChecklist: ["Walking shoes", "Light jacket", "Binoculars", "Camera"],
    waypoints: [
      {
        id: "char-dukan",
        name: "Char Dukan & Sisters Bazaar Loop",
        hindiName: "चार दुकान एवं सिस्टर्स बाज़ार",
        elevation: "2,150 m",
        distance: "2.5 km from Library",
        timeFromPrev: "45 mins",
        difficulty: "Easy paved uphill",
        latitude: 30.4610,
        longitude: 78.0930,
        description: "Colonial-era heritage cluster under pine trees famous for bun maska, apple waffles, and cinnamon tea.",
        imageUrl: "/images/places/mussoorie/lal-tibba.webp",
      },
      {
        id: "lal-tibba",
        name: "Lal Tibba Scenic Viewpoint",
        hindiName: "लाल टिब्बा दृष्टिकोण",
        elevation: "2,275 m",
        distance: "1.5 km",
        timeFromPrev: "30 mins",
        difficulty: "Easy walk",
        latitude: 30.4660,
        longitude: 78.1010,
        description: "Highest point in Mussoorie with high-powered telescopes framing Bandarpoonch and Kedarnath peaks.",
        imageUrl: "/images/places/mussoorie/kempty-falls.webp",
      },
      {
        id: "george-everest",
        name: "George Everest Peak & Wish Well",
        hindiName: "जॉर्ज एवरेस्ट शिखर",
        elevation: "2,250 m",
        distance: "4.0 km",
        timeFromPrev: "1 hr",
        difficulty: "Easy ridge trail",
        latitude: 30.4570,
        longitude: 78.0280,
        description: "Panoramic cliff ridge between the Doon Valley and Aglar River valley offering magical winterline sunsets.",
        imageUrl: "/images/places/mussoorie/company-garden.webp",
      },
    ],
  },
  leh: {
    hasTrek: true,
    title: "Spituk to Stok Valley High-Altitude Ridge Trail",
    hindiTitle: "स्पितुक से स्तोक घाटी अल्पाइन मार्ग",
    trailSummary: "High-altitude trans-Himalayan trail connecting ancient Spituk Monastery with Stok royal village along rugged Indus canyons and barren moonscapes.",
    baseCamp: "Spituk Village (3,300 m)",
    elevationGain: "+400 m",
    peakAltitude: "3,700 m",
    distance: "11 km",
    duration: "4.5 – 6 Hours",
    difficulty: "Alpine / Demanding",
    bestSeason: "June to September",
    approachTransport: "Local taxi from Leh Main Bazaar to Spituk bridge. Return cab from Stok Palace.",
    packingChecklist: ["Polarized sunglasses (Cat 3/4)", "Warm layers", "High SPF sunblock", "Electrolyte water", "Acclimatized baseline"],
    waypoints: [
      {
        id: "spituk-start",
        name: "Spituk Gompa (11th Century)",
        hindiName: "स्पितुक गोम्पा",
        elevation: "3,300 m",
        distance: "0 km",
        timeFromPrev: "Start",
        difficulty: "Easy",
        latitude: 34.1280,
        longitude: 77.5250,
        description: "Iconic cliffside monastery overlooking the turquoise Indus river with fierce Mahakala guardian deity shrine.",
        imageUrl: "/images/places/leh/pangong-tso.webp",
      },
      {
        id: "stok-canyon",
        name: "Stok Valley Moonscape Canyon",
        hindiName: "स्तोक घाटी कैन्यन",
        elevation: "3,550 m",
        distance: "6.0 km",
        timeFromPrev: "2.5 hrs",
        difficulty: "Moderate arid terrain",
        latitude: 34.0500,
        longitude: 77.5600,
        description: "Dramatic ochre and purple rock formations with prayer flags flapping in crisp Himalayan winds.",
        imageUrl: "/images/places/leh/leh-palace.webp",
      },
      {
        id: "stok-palace",
        name: "Stok Royal Palace & Museum",
        hindiName: "स्तोक राजमहल",
        elevation: "3,650 m",
        distance: "5.0 km",
        timeFromPrev: "2 hrs",
        difficulty: "Moderate",
        latitude: 34.0020,
        longitude: 77.5670,
        description: "Seat of the Ladakh Royal Family showcasing antique thangkas, crowns, and jade ornaments.",
        imageUrl: "/images/places/leh/nubra-valley.webp",
      },
    ],
  },
  spiti: {
    hasTrek: true,
    title: "Dhankar Lake & Key Gompa Ridge Trail",
    hindiTitle: "धनखड़ झील एवं की गोम्पा रिज मार्ग",
    trailSummary: "Cold-desert high altitude trek ascending steep rocky switchbacks from ancient cliff-hanging Dhankar Monastery to the emerald, crystal-clear Dhankar alpine lake at 4,270m.",
    baseCamp: "Dhankar Old Gompa (3,894 m)",
    elevationGain: "+376 m",
    peakAltitude: "4,270 m (14,000 ft)",
    distance: "3.5 km round trip",
    duration: "2.5 – 3.5 Hours",
    difficulty: "Alpine / Demanding",
    bestSeason: "June to October",
    approachTransport: "4x4 taxi from Kaza to Dhankar village. Trek starts from the monastery gate.",
    packingChecklist: ["Windproof fleece", "Insulated water flask", "Trekking pole", "UV sunglasses", "Lip balm"],
    waypoints: [
      {
        id: "dhankar-base",
        name: "Dhankar Monastery (Cliff Fortress)",
        hindiName: "धनखड़ गोम्पा",
        elevation: "3,894 m",
        distance: "0 km",
        timeFromPrev: "Start",
        difficulty: "Easy",
        latitude: 32.0200,
        longitude: 78.2100,
        description: "1,200-year-old monastery perched dramatically on mud-spire cliff ridges overlooking the Spiti-Pin confluence.",
        imageUrl: "/images/places/spiti/key-monastery.webp",
      },
      {
        id: "dhankar-lake",
        name: "Dhankar Alpine Lake (4,270 m)",
        hindiName: "धनखड़ अल्पाइन झील",
        elevation: "4,270 m",
        distance: "1.75 km steep ascent",
        timeFromPrev: "1.5 hrs",
        difficulty: "Steep scree ascent",
        latitude: 32.0350,
        longitude: 78.2250,
        description: "Pristine, mirror-like high altitude glacial lake reflecting snow peaks in absolute trans-Himalayan silence.",
        imageUrl: "/images/places/spiti/chandratal-lake.webp",
      },
    ],
  },
  munnar: {
    hasTrek: true,
    title: "Anamudi Shola & Meesapulimala Tea Ridge Trail",
    hindiTitle: "अनामुडी शोला एवं मीसापुलिमला चाय रिज मार्ग",
    trailSummary: "Trek through misty rolling tea plantations and endemic Shola cloud forests up to high ridge viewpoints with sightings of the endangered Nilgiri Tahr.",
    baseCamp: "Munnar Tea Town / Silent Valley Road (1,600 m)",
    elevationGain: "+650 m",
    peakAltitude: "2,250 m",
    distance: "8.5 km",
    duration: "4 – 5 Hours",
    difficulty: "Moderate",
    bestSeason: "September to May",
    approachTransport: "Jeep from Munnar town to estate base. Forest permit required for national park sectors.",
    packingChecklist: ["Rain jacket", "Walking shoes with grip", "Leech socks (monsoon)", "Camera"],
    waypoints: [
      {
        id: "tea-estate",
        name: "KDHP Tea Plantation Valley",
        hindiName: "चाय बागान घाटी",
        elevation: "1,650 m",
        distance: "0 km",
        timeFromPrev: "Start",
        difficulty: "Easy",
        latitude: 10.0880,
        longitude: 77.0600,
        description: "Manicured emerald green tea slopes with aromatic cardamom and silver oak shade trees.",
        imageUrl: "/images/places/munnar/tea-gardens.webp",
      },
      {
        id: "shola-forest",
        name: "Shola Grassland & Mist Ridge",
        hindiName: "शोला घास के मैदान",
        elevation: "2,100 m",
        distance: "4.5 km",
        timeFromPrev: "2 hrs",
        difficulty: "Moderate uphill",
        latitude: 10.1200,
        longitude: 77.0800,
        description: "Unique high-altitude tropical montane cloud forest with endemic orchids and wildlife.",
        imageUrl: "/images/places/munnar/eravikulam-national-park.webp",
      },
    ],
  },
};

export const DEFAULT_NON_TREK_NOTICE: Record<string, DestinationTrekInfo> = {
  jaipur: {
    hasTrek: false,
    title: "Trekking Not Applicable in Jaipur",
    hindiTitle: "जयपुर में पदयात्रा मार्ग लागू नहीं",
    trailSummary: "Jaipur is an urban heritage royal sanctuary best experienced through fort rampart walks, palace courtyards, and bazaar food trails rather than wilderness mountain trekking.",
    baseCamp: "Pink City Walled Quarter",
    elevationGain: "N/A",
    peakAltitude: "431 m",
    distance: "N/A",
    duration: "N/A",
    difficulty: "Easy",
    bestSeason: "October to March",
    approachTransport: "Auto-rickshaws, metro, and heritage walking.",
    packingChecklist: [],
    waypoints: [],
    nonTrekNotice: {
      heading: "Heritage City — Wilderness Trek Unavailable",
      explanation: "Jaipur is renowned for royal palaces, desert forts, and bazaars. Instead of a mountain trek, explore the 1-Day Royal Round Trip or Fort Ramparts walk at Amer and Nahargarh.",
      alternativeMode: "oneday",
    },
  },
  udaipur: {
    hasTrek: false,
    title: "Trekking Not Applicable in Udaipur",
    hindiTitle: "उदयपुर में पदयात्रा मार्ग लागू नहीं",
    trailSummary: "Udaipur is the City of Lakes and royal Mewar palaces. Exploration is centered around lake ferries, rooftop dining, and marble palace courtyards.",
    baseCamp: "Lal Ghat & Lake Pichola",
    elevationGain: "N/A",
    peakAltitude: "598 m",
    distance: "N/A",
    duration: "N/A",
    difficulty: "Easy",
    bestSeason: "September to March",
    approachTransport: "Lakeside walking and boat cruises.",
    packingChecklist: [],
    waypoints: [],
    nonTrekNotice: {
      heading: "Lakeside Sanctuary — Wilderness Trek Unavailable",
      explanation: "Udaipur's charm lies in its shimmering lakes, havelis, and palace courtyards. Switch to the One-Day Round Trip mode for a seamless same-day itinerary.",
      alternativeMode: "oneday",
    },
  },
  varanasi: {
    hasTrek: false,
    title: "Trekking Not Applicable in Varanasi",
    hindiTitle: "वाराणसी में पदयात्रा मार्ग लागू नहीं",
    trailSummary: "Varanasi is an ancient sacred riverfront city. Exploration is conducted along river ghat steps, labyrinthine old-city galiyan, and dawn boat rides.",
    baseCamp: "Dashashwamedh Ghat",
    elevationGain: "N/A",
    peakAltitude: "80 m",
    distance: "N/A",
    duration: "N/A",
    difficulty: "Easy",
    bestSeason: "October to March",
    approachTransport: "Row boats, cycle rickshaws, and walking.",
    packingChecklist: [],
    waypoints: [],
    nonTrekNotice: {
      heading: "Riverfront Sanctuary — Wilderness Trek Unavailable",
      explanation: "Varanasi is explored via dawn boat rides and ghat-to-ghat walks along the holy Ganga. Switch to the One-Day Round Trip mode for the complete spiritual journey.",
      alternativeMode: "oneday",
    },
  },
  goa: {
    hasTrek: false,
    title: "Trekking Not Applicable in Coastal Goa",
    hindiTitle: "तटीय गोवा में पर्वतीय पदयात्रा लागू नहीं",
    trailSummary: "Goa is a coastal and heritage sanctuary best explored via scooter rides, beach walks, Latin Quarter strolls, and waterfall day trips.",
    baseCamp: "Panjim & Coastal Belt",
    elevationGain: "N/A",
    peakAltitude: "10 m",
    distance: "N/A",
    duration: "N/A",
    difficulty: "Easy",
    bestSeason: "November to February",
    approachTransport: "Rented scooters, motorbikes, and taxis.",
    packingChecklist: [],
    waypoints: [],
    nonTrekNotice: {
      heading: "Coastal Sanctuary — Mountain Trek Unavailable",
      explanation: "Goa offers coastal cliff strolls and Latin Quarter haveli walks rather than high alpine trails. Switch to the One-Day Round Trip mode for a curated day itinerary.",
      alternativeMode: "oneday",
    },
  },
};

export const DESTINATION_DAY_TRIPS: Record<string, DestinationDayTrip> = {
  varanasi: {
    title: "The Eternal Varanasi 1-Day Journey",
    hindiTitle: "काशी एक दिवसीय समग्र यात्रा",
    tagline: "Dawn boat ride on the sacred Ganga, Kashi Vishwanath puja, old city kachoris, and evening Dashashwamedh Maha Aarti.",
    estimatedHours: "14 Hours (Full Day)",
    transitContext: "Walk along the ghats and old galiyan; shared boat between Dashashwamedh and Assi; auto-rickshaw to Sarnath.",
    totalDistance: "18 km total travel perimeter",
    blocks: [
      {
        time: "05:30 – 08:00 AM",
        period: "DAWN",
        title: "Dawn Wooden Boat Ride & Assi Sunrise",
        hindiTitle: "दशाश्वमेध से अस्सी नौका विहार",
        activity: "Board a traditional hand-rowed wooden boat at Dashashwamedh Ghat as dawn breaks. Watch morning rituals, yogis, and sacred chants reflecting on the calm river.",
        location: "Dashashwamedh to Assi Ghat",
        highlight: "Golden sunrise illumination across 84 ancient stone ghats",
        duration: "2.5 Hours",
        tips: "Negotiate boat rate beforehand (₹300–500 for shared/private). Bring a light shawl for cool river mist.",
        iconType: "sunrise",
      },
      {
        time: "08:30 – 11:30 AM",
        period: "MORNING",
        title: "Kashi Vishwanath Corridor & Kachori Gali",
        hindiTitle: "काशी विश्वनाथ दर्शन एवं कचौड़ी गली",
        activity: "Walk through the newly restored gold-spired Kashi Vishwanath temple corridor. Follow with breakfast of piping hot hing kachoris and jalebis in Kachori Gali.",
        location: "Kashi Vishwanath Complex & Thatheri Bazaar",
        highlight: "Sacred Jyotirlinga darshan & authentic Banarasi hing kachori",
        duration: "3.0 Hours",
        tips: "Mobile phones and leather goods are deposited in secure lockers before entering the temple.",
        iconType: "landmark",
      },
      {
        time: "12:00 – 02:00 PM",
        period: "MIDDAY",
        title: "Blue Lassi, Malaiyyo & Banarasi Silk Looms",
        hindiTitle: "मलाईदार लस्सी एवं बनारसी सिल्क",
        activity: "Sip thick clay-pot Blue Lassi topped with fresh pomegranate and pistachios near Manikarnika. Visit local master silk weavers weaving Zari brocades.",
        location: "Chowk & Bangali Tola",
        highlight: "Authentic clay-pot lassi and handmade Banarasi silk handlooms",
        duration: "2.0 Hours",
        tips: "Look for government-certified handloom cooperatives to support local artisan weavers.",
        iconType: "food",
      },
      {
        time: "02:30 – 05:00 PM",
        period: "AFTERNOON",
        title: "Sarnath Deer Park & Dhamek Stupa Excursion",
        hindiTitle: "सारनाथ धमेक स्तूप दर्शन",
        activity: "Short 10 km auto-rickshaw ride to Sarnath, where Lord Buddha gave his first sermon. Explore the 5th-century Dhamek Stupa and Ashoka Lion Capital museum.",
        location: "Sarnath Archaeological Enclave",
        highlight: "Ancient Ashoka Pillar & peaceful monastic gardens",
        duration: "2.5 Hours",
        tips: "The Sarnath Archaeological Museum is open until 05:00 PM (closed Fridays).",
        iconType: "nature",
      },
      {
        time: "06:30 – 08:00 PM",
        period: "SUNSET",
        title: "Dashashwamedh Ghat Maha Ganga Aarti",
        hindiTitle: "दशाश्वमेध महा गंगा आरती",
        activity: "Witness the synchronized grand brass lamp Aarti performed by saffron-clad priests amidst conch shells, incense smoke, and ringing temple bells.",
        location: "Dashashwamedh Main Ghat",
        highlight: "Spiritual crescendo with thousands of floating marigold diyas",
        duration: "1.5 Hours",
        tips: "Arrive by 05:45 PM for prime front-row ghat step seating or view from a moored boat.",
        iconType: "sunset",
      },
      {
        time: "08:30 – 10:00 PM",
        period: "NIGHT",
        title: "Baati Chokha Dinner & Quiet Night Ghat Stroll",
        hindiTitle: "बाटी चोखा रात्रि भोजन एवं शांत घाट",
        activity: "Enjoy roasted sattu baatis with smoky baingan chokha and desi ghee. Conclude with a quiet midnight walk along peaceful Assi Ghat steps.",
        location: "Assi Ghat & Bhelupur",
        highlight: "Traditional Purvanchali cuisine and reflective nocturnal river silence",
        duration: "1.5 Hours",
        tips: "Conclude with an authentic Meetha Banarasi Paan at Godowlia Chowk.",
        iconType: "night",
      },
    ],
  },
  jaipur: {
    title: "The Royal Rajputana 1-Day Journey",
    hindiTitle: "जयपुर एक दिवसीय शाही यात्रा",
    tagline: "Nahargarh dawn ramparts, Pyaaz Kachori breakfast, Amber Fort grandeur, Hawa Mahal rooftop chai, and Johari Bazaar artisan shopping.",
    estimatedHours: "13 Hours (Full Day)",
    transitContext: "Auto-rickshaw or taxi between forts; walking inside the Pink City walled markets.",
    totalDistance: "25 km round trip perimeter",
    blocks: [
      {
        time: "06:30 – 08:30 AM",
        period: "DAWN",
        title: "Nahargarh Fort Sunrise & Aravalli Vista",
        hindiTitle: "नाहरगढ़ सूर्योदय एवं अरावली दृश्य",
        activity: "Drive up the winding Aravalli ridge to Padao viewpoint at Nahargarh Fort for a sweeping sunrise view over the entire Pink City waking up below.",
        location: "Nahargarh Fort Ridge",
        highlight: "Crisp mountain breeze and panoramic sunrise over the terracotta city",
        duration: "2.0 Hours",
        tips: "Morning cycling groups often ride up Nahargarh road. Wear a light windbreaker.",
        iconType: "sunrise",
      },
      {
        time: "09:00 – 10:00 AM",
        period: "MORNING",
        title: "Rawat Pyaaz Kachori & Masala Chai Breakfast",
        hindiTitle: "रावत प्याज़ कचौड़ी एवं मसाला चाय",
        activity: "Stop at legendary Rawat Mishthan Bhandar for golden crispy onion kachoris, mawa kachoris, and freshly brewed saffron masala chai.",
        location: "Station Road / Sindhi Camp",
        highlight: "Iconic Jaipur pyaaz kachori with sweet tamarind chutney",
        duration: "1.0 Hour",
        tips: "Ask for freshly fried batches straight out of the kadhai.",
        iconType: "food",
      },
      {
        time: "10:30 AM – 01:30 PM",
        period: "MORNING",
        title: "Amber Fort & Sheesh Mahal Grandeur",
        hindiTitle: "आमेर किला एवं शीश महल",
        activity: "Explore the UNESCO-listed Amber Fort palace complex, including Ganesh Pol gate, the mirror-inlaid Sheesh Mahal, and view of Maota Lake.",
        location: "Amer Royal Precinct",
        highlight: "Dazzling mirror reflections inside Sheesh Mahal",
        duration: "3.0 Hours",
        tips: "Hire an official Rajasthan Tourism certified guide at the main courtyard gate.",
        iconType: "landmark",
      },
      {
        time: "02:00 – 04:00 PM",
        period: "MIDDAY",
        title: "City Palace Courtyards & Jantar Mantar",
        hindiTitle: "सिटी पैलेस एवं जंतर मंतर",
        activity: "Visit the royal Peacock Courtyard at City Palace and the ancient UNESCO astronomical sun-dials at Jantar Mantar.",
        location: "Old City Walled Precinct",
        highlight: "Pritam Niwas Chowk peacock gate and world's largest stone sundial",
        duration: "2.0 Hours",
        tips: "Combined ticket includes Jantar Mantar and Hawa Mahal.",
        iconType: "landmark",
      },
      {
        time: "04:30 – 06:30 PM",
        period: "SUNSET",
        title: "Hawa Mahal Wind Palace & Rooftop Chai",
        hindiTitle: "हवा महल एवं रूफटॉप चाय",
        activity: "Admire the 953 jharokha honeycomb pink sandstone facade of Hawa Mahal. Enjoy sunset tea from a rooftop café across the boulevard.",
        location: "Badi Chaupar",
        highlight: "Golden hour glow lighting up the terracotta honeycomb facade",
        duration: "2.0 Hours",
        tips: "Wind View Cafe or Tattoo Cafe across the street offer the best straight-on photo angles.",
        iconType: "sunset",
      },
      {
        time: "07:00 – 09:30 PM",
        period: "NIGHT",
        title: "Johari Bazaar Block Prints & Dal Baati Dinner",
        hindiTitle: "जौहरी बाज़ार एवं पारंपरिक दाल बाटी थाली",
        activity: "Stroll through Johari and Bapu Bazaars for blue pottery, block-print quilts, and silver jewelry. Conclude with an authentic Rajasthani Dal Baati Churma feast.",
        location: "Johari Bazaar & MI Road",
        highlight: "Pure desi ghee dal baati, gatte ki sabzi, and creamy Lassiwala lassi",
        duration: "2.5 Hours",
        tips: "Lassiwala on MI Road closes once their daily hand-churned batch runs out.",
        iconType: "night",
      },
    ],
  },
  udaipur: {
    title: "The Romantic Lake Pichola 1-Day Journey",
    hindiTitle: "उदयपुर एक दिवसीय झील यात्रा",
    tagline: "Ambrai Ghat morning serenity, City Palace marble corridors, Lake Pichola royal cruise, and Sajjangarh Monsoon Palace sunset.",
    estimatedHours: "12 Hours (Full Day)",
    transitContext: "Narrow old-city lanes are walking-only; auto-rickshaw to Sajjangarh Monsoon Palace; boat on Lake Pichola.",
    totalDistance: "15 km round trip perimeter",
    blocks: [
      {
        time: "06:30 – 08:00 AM",
        period: "DAWN",
        title: "Ambrai Ghat Dawn Calm & Lake Reflection",
        hindiTitle: "अम्ब्राई घाट प्रातःकालीन शांति",
        activity: "Begin at Ambrai Ghat opposite City Palace. Watch white marble domes and the Lake Palace reflect in glass-still water in dawn mist.",
        location: "Ambrai Ghat, Old City",
        highlight: "Pristine reflections of City Palace across Lake Pichola",
        duration: "1.5 Hours",
        tips: "Quiet early mornings are free of afternoon crowds. Perfect for photography.",
        iconType: "sunrise",
      },
      {
        time: "08:30 – 11:30 AM",
        period: "MORNING",
        title: "City Palace Marble Museum & Jagdish Temple",
        hindiTitle: "सिटी पैलेस एवं जगदीश मंदिर",
        activity: "Tour Rajasthan's largest palace complex with ornate silver galleries, mirror mosaics, and royal courtyards, followed by 1651 AD Jagdish stone temple.",
        location: "City Palace Complex & Jagdish Chowk",
        highlight: "Mor Chowk peacock mosaics & Zenana Mahal courtyards",
        duration: "3.0 Hours",
        tips: "Remove shoes before climbing the steep stone steps to Jagdish Temple.",
        iconType: "landmark",
      },
      {
        time: "12:00 – 02:00 PM",
        period: "MIDDAY",
        title: "Mewari Dal Baati & Lakeside Rooftop Lunch",
        hindiTitle: "मेवाड़ी दाल बाटी एवं रूफटॉप दोपहर भोजन",
        activity: "Savor piping hot Mewari Dal Baati Churma, Ker Sangri, and cold chaas on an open rooftop café overlooking Lake Pichola.",
        location: "Lal Ghat & Gangaur Ghat",
        highlight: "Authentic five-lentil dal with wood-baked baatis dipped in ghee",
        duration: "2.0 Hours",
        tips: "Traditional Krishna Dal Baati Restro provides authentic local flavours.",
        iconType: "food",
      },
      {
        time: "02:30 – 04:30 PM",
        period: "AFTERNOON",
        title: "Lake Pichola Royal Boat Cruise & Jag Mandir",
        hindiTitle: "पिछोला नौका विहार एवं जग मंदिर",
        activity: "Board the solar boat cruise from Bansi Ghat around Jag Niwas (Lake Palace) and disembark at island palace Jag Mandir.",
        location: "Bansi Ghat to Jag Mandir Island",
        highlight: "Gliding beside white marble island palaces on crystal lake waters",
        duration: "2.0 Hours",
        tips: "Afternoon breeze on the lake is cool and scenic.",
        iconType: "nature",
      },
      {
        time: "05:00 – 07:00 PM",
        period: "SUNSET",
        title: "Sajjangarh Monsoon Palace High Sunset",
        hindiTitle: "सज्जनगढ़ मानसून पैलेस सूर्यास्त",
        activity: "Ascend the Aravalli mountain top to Monsoon Palace (Sajjangarh) for a dramatic panoramic sunset overlooking all five lakes of Udaipur.",
        location: "Sajjangarh Hill Top (944 m)",
        highlight: "360-degree sunset over the Aravalli mountain ranges and lakes",
        duration: "2.0 Hours",
        tips: "Shared jeeps operate from the sanctuary foothills up to the fort gates.",
        iconType: "sunset",
      },
      {
        time: "07:30 – 09:30 PM",
        period: "NIGHT",
        title: "Dharohar Folk Dance at Bagore Ki Haveli & Dinner",
        hindiTitle: "बागोर की हवेली लोक नृत्य एवं रात्रि भोजन",
        activity: "Watch traditional Rajasthani Bhavai pot-balancing and puppet dance at 18th-century Bagore Ki Haveli, followed by candlelit lakeside dinner.",
        location: "Gangaur Ghat",
        highlight: "Authentic Rajasthani folk dance with 11 brass pots balanced on head",
        duration: "2.0 Hours",
        tips: "Dharohar dance show starts promptly at 07:00 PM; buy tickets by 06:15 PM.",
        iconType: "night",
      },
    ],
  },
  manali: {
    title: "The Alpine Valley Manali 1-Day Journey",
    hindiTitle: "मनाली एक दिवसीय पर्वतीय यात्रा",
    tagline: "Old Manali pine forest stroll, Hadimba pagoda puja, trout fish & siddu lunch, Jogini waterfall hike, and Mall Road evening stroll.",
    estimatedHours: "12 Hours (Full Day)",
    transitContext: "Walk in Old Manali; auto-rickshaw to Vashisht; electric bus or taxi to Solang Valley.",
    totalDistance: "20 km round trip perimeter",
    blocks: [
      {
        time: "06:30 – 08:30 AM",
        period: "DAWN",
        title: "Old Manali Cedar Woods & Mountain Mist Walk",
        hindiTitle: "ओल्ड मनाली देवदार वन पदयात्रा",
        activity: "Crisp morning walk through ancient deodar pine forests along Manalsu river. Listen to roaring glacial currents and birdsong in alpine mist.",
        location: "Old Manali Village & Club House Road",
        highlight: "Crisp oxygen-rich mountain pine aroma and glacier views",
        duration: "2.0 Hours",
        tips: "Wear a warm fleece as morning valley temperatures are chilly.",
        iconType: "sunrise",
      },
      {
        time: "09:00 – 11:30 AM",
        period: "MORNING",
        title: "Hadimba Pagoda Temple & Vashisht Hot Springs",
        hindiTitle: "हडिम्बा काष्ठ मंदिर एवं वशिष्ठ कुंड",
        activity: "Visit the 1553 AD four-tiered carved wooden Hadimba Temple inside sacred cedar groves. Cross the river to Vashisht for natural sulfur hot springs.",
        location: "Dhungri Forest & Vashisht Village",
        highlight: "Ancient Himalayan wood carvings & natural hot sulfur baths",
        duration: "2.5 Hours",
        tips: "Remove leather items and shoes outside temple boundaries.",
        iconType: "landmark",
      },
      {
        time: "12:00 – 02:00 PM",
        period: "MIDDAY",
        title: "Authentic Himachali Siddu & River Trout Lunch",
        hindiTitle: "हिमाचली सिड्डू एवं नदी की ट्राउट मछली",
        activity: "Enjoy steamed Himachali Siddu stuffed with walnut paste and desi ghee, alongside fresh pan-seared Tirthan brown trout at a wooden riverside café.",
        location: "Old Manali Bridge & Clubhouse road",
        highlight: "Traditional walnut-poppy seed Siddu and wood-fired pizza",
        duration: "2.0 Hours",
        tips: "Try authentic local Himachali dhabas near Clubhouse.",
        iconType: "food",
      },
      {
        time: "02:30 – 05:30 PM",
        period: "AFTERNOON",
        title: "Jogini Waterfall Hike or Solang Valley Slopes",
        hindiTitle: "जोगिनी जलप्रपात पदयात्रा",
        activity: "Gentle 3 km forest hike from Vashisht through pine trees to Jogini Waterfall cascading down granite cliffs with valley views.",
        location: "Vashisht to Jogini Waterfall Trail",
        highlight: "Dramatic cascade spray and panoramic views of Rohtang peaks",
        duration: "3.0 Hours",
        tips: "Wear sturdy shoes with good tread for damp stone sections.",
        iconType: "nature",
      },
      {
        time: "06:00 – 07:30 PM",
        period: "SUNSET",
        title: "Mall Road Stroll & Tibetan Monastery Blessing",
        hindiTitle: "मॉल रोड एवं तिब्बती मठ",
        activity: "Spin brass prayer wheels at Gadhan Thekchhokling Gompa. Walk along vehicle-free Mall Road for soft woollen Kullu shawls and roasted pine nuts.",
        location: "Manali Mall Road & Monastery",
        highlight: "Spinning giant Tibetan prayer wheels and mountain souvenir shops",
        duration: "1.5 Hours",
        tips: "Pashmina shawls should carry the official Handloom mark.",
        iconType: "sunset",
      },
      {
        time: "08:00 – 09:30 PM",
        period: "NIGHT",
        title: "Campfire Dinner & Stargazing Evening",
        hindiTitle: "कैंपफायर रात्रि भोजन एवं तारामंडल",
        activity: "Cozy dinner by a crackling wood fire with hot apple cinnamon tea and stargazing beneath unpolluted Himalayan skies.",
        location: "Old Manali / Log Huts Area",
        highlight: "Clear mountain stargazing and acoustic live music",
        duration: "1.5 Hours",
        tips: "Keep a down jacket ready as evening mountain temperatures drop quickly.",
        iconType: "night",
      },
    ],
  },
  "tungnath-chandrashila": {
    title: "The Sacred Alpine Summit 1-Day Journey",
    hindiTitle: "तुंगनाथ–चंद्रशिला एक दिवसीय शिखर यात्रा",
    tagline: "05:00 AM dawn start from Chopta, Tungnath shrine puja, 360° Chaukhamba sunrise at Chandrashila, and Garhwali mandua roti lunch.",
    estimatedHours: "10 Hours (Full Day Trek)",
    transitContext: "Trek on foot only; registered ponies available from Chopta base up to temple shrine.",
    totalDistance: "10 km round trip walking",
    blocks: [
      {
        time: "05:00 – 07:30 AM",
        period: "DAWN",
        title: "Chopta Dawn Departure & Alpine Forest Ascent",
        hindiTitle: "चोपता से प्रातःकालीन प्रस्थान",
        activity: "Begin the 3.5 km stone-paved ascent from Chopta base camp (2,680m) under towering rhododendron and oak canopies as dawn paints the sky pink.",
        location: "Chopta Trailhead (2,680 m)",
        highlight: "First rays of sunlight touching the snow peaks through pine trees",
        duration: "2.5 Hours",
        tips: "Start by 05:00 AM to reach summit before midday cloud cover gathers.",
        iconType: "sunrise",
      },
      {
        time: "07:30 – 08:45 AM",
        period: "MORNING",
        title: "Tungnath Temple Shrine Puja (3,680 m)",
        hindiTitle: "तुंगनाथ मंदिर दर्शन एवं पूजा",
        activity: "Arrive at the world's highest Shiva shrine. Offer prayers at the ancient thousand-year-old Nagara stone sanctum surrounded by alpine bugyals.",
        location: "Tungnath Temple Precinct (3,680 m)",
        highlight: "Sacred 3rd Panch Kedar stone shrine standing atop the alpine ridge",
        duration: "1.25 Hours",
        tips: "Remove shoes outside temple steps. Carry cash for prasad offerings.",
        iconType: "landmark",
      },
      {
        time: "09:00 – 10:30 AM",
        period: "MORNING",
        title: "Chandrashila 360° Summit Panorama (4,000 m)",
        hindiTitle: "चंद्रशिला शिखर 360° हिमालय दर्शन",
        activity: "Push through the final 1.5 km steep crag ascent to reach the 4,000m Moon Rock summit. Behold the colossal Chaukhamba, Trishul, and Nanda Devi peaks.",
        location: "Chandrashila Summit (4,000 m)",
        highlight: "Unmatched 360-degree panorama of Garhwal Himalayan giants",
        duration: "1.5 Hours",
        tips: "Hold trekking pole securely on the rocky summit crag. Beware of high wind gusts.",
        iconType: "nature",
      },
      {
        time: "10:30 AM – 01:00 PM",
        period: "MIDDAY",
        title: "Descent to Chopta Meadows",
        hindiTitle: "चोपता बुग्याल की ओर वापसी",
        activity: "Careful downhill descent across stone switchbacks, enjoying open meadow views and blooming rhododendron (buransh) groves in spring.",
        location: "Tungnath to Chopta Trail Corridor",
        highlight: "Sweeping views of alpine pastures and Monal pheasant sightings",
        duration: "2.5 Hours",
        tips: "Pace your descent to protect knees; use trekking poles for balance.",
        iconType: "nature",
      },
      {
        time: "01:00 – 02:30 PM",
        period: "AFTERNOON",
        title: "Garhwali Mandua Roti & Pahadi Dal Lunch",
        hindiTitle: "गढ़वाली मंडुआ रोटी एवं पहाड़ी दाल",
        activity: "Warm up at trailside wooden dhabas with hot ginger tea, local finger millet (mandua) rotis, Pahadi rajma, and fresh buransh juice.",
        location: "Chopta Trailhead Dhabas",
        highlight: "Nutritious traditional Garhwali meal after 10 km alpine expedition",
        duration: "1.5 Hours",
        tips: "Try freshly pressed Rhododendron (Buransh) squash.",
        iconType: "food",
      },
      {
        time: "03:00 – 06:00 PM",
        period: "SUNSET",
        title: "Deoria Tal Lake Extension or Sunset Campfire",
        hindiTitle: "देवरिया ताल या सूर्यास्त कैंपफायर",
        activity: "Short 2 km extension hike to tranquil Deoria Tal lake reflecting Chaukhamba peaks in mirror water, followed by an evening campfire at Chopta base.",
        location: "Sari Village / Deoria Tal (2,438 m)",
        highlight: "Chaukhamba reflection in emerald lake water at sunset",
        duration: "3.0 Hours",
        tips: "Carry torchlight if returning from Deoria Tal after sunset.",
        iconType: "sunset",
      },
    ],
  },
};
